/*
 * Dev Store API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.9.1
 * Contact: admin@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.woocommerce.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.net.URI;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.woocommerce.JSON;

/**
 * Theme.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.20.0-SNAPSHOT")
public class WooCommerceSystemStatusTheme {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nullable
  private String name;

  public static final String SERIALIZED_NAME_VERSION = "version";
  @SerializedName(SERIALIZED_NAME_VERSION)
  @javax.annotation.Nullable
  private String version;

  public static final String SERIALIZED_NAME_VERSION_LATEST = "version_latest";
  @SerializedName(SERIALIZED_NAME_VERSION_LATEST)
  @javax.annotation.Nullable
  private String versionLatest;

  public static final String SERIALIZED_NAME_AUTHOR_URL = "author_url";
  @SerializedName(SERIALIZED_NAME_AUTHOR_URL)
  @javax.annotation.Nullable
  private URI authorUrl;

  public static final String SERIALIZED_NAME_IS_CHILD_THEME = "is_child_theme";
  @SerializedName(SERIALIZED_NAME_IS_CHILD_THEME)
  @javax.annotation.Nullable
  private Boolean isChildTheme;

  public static final String SERIALIZED_NAME_IS_BLOCK_THEME = "is_block_theme";
  @SerializedName(SERIALIZED_NAME_IS_BLOCK_THEME)
  @javax.annotation.Nullable
  private Boolean isBlockTheme;

  public static final String SERIALIZED_NAME_HAS_WOOCOMMERCE_SUPPORT = "has_woocommerce_support";
  @SerializedName(SERIALIZED_NAME_HAS_WOOCOMMERCE_SUPPORT)
  @javax.annotation.Nullable
  private Boolean hasWoocommerceSupport;

  public static final String SERIALIZED_NAME_HAS_WOOCOMMERCE_FILE = "has_woocommerce_file";
  @SerializedName(SERIALIZED_NAME_HAS_WOOCOMMERCE_FILE)
  @javax.annotation.Nullable
  private Boolean hasWoocommerceFile;

  public static final String SERIALIZED_NAME_HAS_OUTDATED_TEMPLATES = "has_outdated_templates";
  @SerializedName(SERIALIZED_NAME_HAS_OUTDATED_TEMPLATES)
  @javax.annotation.Nullable
  private Boolean hasOutdatedTemplates;

  public static final String SERIALIZED_NAME_OVERRIDES = "overrides";
  @SerializedName(SERIALIZED_NAME_OVERRIDES)
  @javax.annotation.Nullable
  private List<String> overrides = new ArrayList<>();

  public static final String SERIALIZED_NAME_PARENT_NAME = "parent_name";
  @SerializedName(SERIALIZED_NAME_PARENT_NAME)
  @javax.annotation.Nullable
  private String parentName;

  public static final String SERIALIZED_NAME_PARENT_VERSION = "parent_version";
  @SerializedName(SERIALIZED_NAME_PARENT_VERSION)
  @javax.annotation.Nullable
  private String parentVersion;

  public static final String SERIALIZED_NAME_PARENT_AUTHOR_URL = "parent_author_url";
  @SerializedName(SERIALIZED_NAME_PARENT_AUTHOR_URL)
  @javax.annotation.Nullable
  private URI parentAuthorUrl;

  public WooCommerceSystemStatusTheme() {
  }

  public WooCommerceSystemStatusTheme name(@javax.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * Theme name.
   * @return name
   */
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }


  public WooCommerceSystemStatusTheme version(@javax.annotation.Nullable String version) {
    this.version = version;
    return this;
  }

  /**
   * Theme version.
   * @return version
   */
  @javax.annotation.Nullable
  public String getVersion() {
    return version;
  }

  public void setVersion(@javax.annotation.Nullable String version) {
    this.version = version;
  }


  public WooCommerceSystemStatusTheme versionLatest(@javax.annotation.Nullable String versionLatest) {
    this.versionLatest = versionLatest;
    return this;
  }

  /**
   * Latest version of theme.
   * @return versionLatest
   */
  @javax.annotation.Nullable
  public String getVersionLatest() {
    return versionLatest;
  }

  public void setVersionLatest(@javax.annotation.Nullable String versionLatest) {
    this.versionLatest = versionLatest;
  }


  public WooCommerceSystemStatusTheme authorUrl(@javax.annotation.Nullable URI authorUrl) {
    this.authorUrl = authorUrl;
    return this;
  }

  /**
   * Theme author URL.
   * @return authorUrl
   */
  @javax.annotation.Nullable
  public URI getAuthorUrl() {
    return authorUrl;
  }

  public void setAuthorUrl(@javax.annotation.Nullable URI authorUrl) {
    this.authorUrl = authorUrl;
  }


  public WooCommerceSystemStatusTheme isChildTheme(@javax.annotation.Nullable Boolean isChildTheme) {
    this.isChildTheme = isChildTheme;
    return this;
  }

  /**
   * Is this theme a child theme?
   * @return isChildTheme
   */
  @javax.annotation.Nullable
  public Boolean getIsChildTheme() {
    return isChildTheme;
  }

  public void setIsChildTheme(@javax.annotation.Nullable Boolean isChildTheme) {
    this.isChildTheme = isChildTheme;
  }


  public WooCommerceSystemStatusTheme isBlockTheme(@javax.annotation.Nullable Boolean isBlockTheme) {
    this.isBlockTheme = isBlockTheme;
    return this;
  }

  /**
   * Is this theme a block theme?
   * @return isBlockTheme
   */
  @javax.annotation.Nullable
  public Boolean getIsBlockTheme() {
    return isBlockTheme;
  }

  public void setIsBlockTheme(@javax.annotation.Nullable Boolean isBlockTheme) {
    this.isBlockTheme = isBlockTheme;
  }


  public WooCommerceSystemStatusTheme hasWoocommerceSupport(@javax.annotation.Nullable Boolean hasWoocommerceSupport) {
    this.hasWoocommerceSupport = hasWoocommerceSupport;
    return this;
  }

  /**
   * Does the theme declare WooCommerce support?
   * @return hasWoocommerceSupport
   */
  @javax.annotation.Nullable
  public Boolean getHasWoocommerceSupport() {
    return hasWoocommerceSupport;
  }

  public void setHasWoocommerceSupport(@javax.annotation.Nullable Boolean hasWoocommerceSupport) {
    this.hasWoocommerceSupport = hasWoocommerceSupport;
  }


  public WooCommerceSystemStatusTheme hasWoocommerceFile(@javax.annotation.Nullable Boolean hasWoocommerceFile) {
    this.hasWoocommerceFile = hasWoocommerceFile;
    return this;
  }

  /**
   * Does the theme have a woocommerce.php file?
   * @return hasWoocommerceFile
   */
  @javax.annotation.Nullable
  public Boolean getHasWoocommerceFile() {
    return hasWoocommerceFile;
  }

  public void setHasWoocommerceFile(@javax.annotation.Nullable Boolean hasWoocommerceFile) {
    this.hasWoocommerceFile = hasWoocommerceFile;
  }


  public WooCommerceSystemStatusTheme hasOutdatedTemplates(@javax.annotation.Nullable Boolean hasOutdatedTemplates) {
    this.hasOutdatedTemplates = hasOutdatedTemplates;
    return this;
  }

  /**
   * Does this theme have outdated templates?
   * @return hasOutdatedTemplates
   */
  @javax.annotation.Nullable
  public Boolean getHasOutdatedTemplates() {
    return hasOutdatedTemplates;
  }

  public void setHasOutdatedTemplates(@javax.annotation.Nullable Boolean hasOutdatedTemplates) {
    this.hasOutdatedTemplates = hasOutdatedTemplates;
  }


  public WooCommerceSystemStatusTheme overrides(@javax.annotation.Nullable List<String> overrides) {
    this.overrides = overrides;
    return this;
  }

  public WooCommerceSystemStatusTheme addOverridesItem(String overridesItem) {
    if (this.overrides == null) {
      this.overrides = new ArrayList<>();
    }
    this.overrides.add(overridesItem);
    return this;
  }

  /**
   * Template overrides.
   * @return overrides
   */
  @javax.annotation.Nullable
  public List<String> getOverrides() {
    return overrides;
  }

  public void setOverrides(@javax.annotation.Nullable List<String> overrides) {
    this.overrides = overrides;
  }


  public WooCommerceSystemStatusTheme parentName(@javax.annotation.Nullable String parentName) {
    this.parentName = parentName;
    return this;
  }

  /**
   * Parent theme name.
   * @return parentName
   */
  @javax.annotation.Nullable
  public String getParentName() {
    return parentName;
  }

  public void setParentName(@javax.annotation.Nullable String parentName) {
    this.parentName = parentName;
  }


  public WooCommerceSystemStatusTheme parentVersion(@javax.annotation.Nullable String parentVersion) {
    this.parentVersion = parentVersion;
    return this;
  }

  /**
   * Parent theme version.
   * @return parentVersion
   */
  @javax.annotation.Nullable
  public String getParentVersion() {
    return parentVersion;
  }

  public void setParentVersion(@javax.annotation.Nullable String parentVersion) {
    this.parentVersion = parentVersion;
  }


  public WooCommerceSystemStatusTheme parentAuthorUrl(@javax.annotation.Nullable URI parentAuthorUrl) {
    this.parentAuthorUrl = parentAuthorUrl;
    return this;
  }

  /**
   * Parent theme author URL.
   * @return parentAuthorUrl
   */
  @javax.annotation.Nullable
  public URI getParentAuthorUrl() {
    return parentAuthorUrl;
  }

  public void setParentAuthorUrl(@javax.annotation.Nullable URI parentAuthorUrl) {
    this.parentAuthorUrl = parentAuthorUrl;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the WooCommerceSystemStatusTheme instance itself
   */
  public WooCommerceSystemStatusTheme putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WooCommerceSystemStatusTheme systemStatusTheme = (WooCommerceSystemStatusTheme) o;
    return Objects.equals(this.name, systemStatusTheme.name) &&
        Objects.equals(this.version, systemStatusTheme.version) &&
        Objects.equals(this.versionLatest, systemStatusTheme.versionLatest) &&
        Objects.equals(this.authorUrl, systemStatusTheme.authorUrl) &&
        Objects.equals(this.isChildTheme, systemStatusTheme.isChildTheme) &&
        Objects.equals(this.isBlockTheme, systemStatusTheme.isBlockTheme) &&
        Objects.equals(this.hasWoocommerceSupport, systemStatusTheme.hasWoocommerceSupport) &&
        Objects.equals(this.hasWoocommerceFile, systemStatusTheme.hasWoocommerceFile) &&
        Objects.equals(this.hasOutdatedTemplates, systemStatusTheme.hasOutdatedTemplates) &&
        Objects.equals(this.overrides, systemStatusTheme.overrides) &&
        Objects.equals(this.parentName, systemStatusTheme.parentName) &&
        Objects.equals(this.parentVersion, systemStatusTheme.parentVersion) &&
        Objects.equals(this.parentAuthorUrl, systemStatusTheme.parentAuthorUrl)&&
        Objects.equals(this.additionalProperties, systemStatusTheme.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, version, versionLatest, authorUrl, isChildTheme, isBlockTheme, hasWoocommerceSupport, hasWoocommerceFile, hasOutdatedTemplates, overrides, parentName, parentVersion, parentAuthorUrl, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WooCommerceSystemStatusTheme {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    versionLatest: ").append(toIndentedString(versionLatest)).append("\n");
    sb.append("    authorUrl: ").append(toIndentedString(authorUrl)).append("\n");
    sb.append("    isChildTheme: ").append(toIndentedString(isChildTheme)).append("\n");
    sb.append("    isBlockTheme: ").append(toIndentedString(isBlockTheme)).append("\n");
    sb.append("    hasWoocommerceSupport: ").append(toIndentedString(hasWoocommerceSupport)).append("\n");
    sb.append("    hasWoocommerceFile: ").append(toIndentedString(hasWoocommerceFile)).append("\n");
    sb.append("    hasOutdatedTemplates: ").append(toIndentedString(hasOutdatedTemplates)).append("\n");
    sb.append("    overrides: ").append(toIndentedString(overrides)).append("\n");
    sb.append("    parentName: ").append(toIndentedString(parentName)).append("\n");
    sb.append("    parentVersion: ").append(toIndentedString(parentVersion)).append("\n");
    sb.append("    parentAuthorUrl: ").append(toIndentedString(parentAuthorUrl)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("name", "version", "version_latest", "author_url", "is_child_theme", "is_block_theme", "has_woocommerce_support", "has_woocommerce_file", "has_outdated_templates", "overrides", "parent_name", "parent_version", "parent_author_url"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to WooCommerceSystemStatusTheme
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!WooCommerceSystemStatusTheme.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in WooCommerceSystemStatusTheme is not found in the empty JSON string", WooCommerceSystemStatusTheme.openapiRequiredFields.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("version") != null && !jsonObj.get("version").isJsonNull()) && !jsonObj.get("version").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `version` to be a primitive type in the JSON string but got `%s`", jsonObj.get("version").toString()));
      }
      if ((jsonObj.get("version_latest") != null && !jsonObj.get("version_latest").isJsonNull()) && !jsonObj.get("version_latest").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `version_latest` to be a primitive type in the JSON string but got `%s`", jsonObj.get("version_latest").toString()));
      }
      if ((jsonObj.get("author_url") != null && !jsonObj.get("author_url").isJsonNull()) && !jsonObj.get("author_url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `author_url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("author_url").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("overrides") != null && !jsonObj.get("overrides").isJsonNull() && !jsonObj.get("overrides").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `overrides` to be an array in the JSON string but got `%s`", jsonObj.get("overrides").toString()));
      }
      if ((jsonObj.get("parent_name") != null && !jsonObj.get("parent_name").isJsonNull()) && !jsonObj.get("parent_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `parent_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("parent_name").toString()));
      }
      if ((jsonObj.get("parent_version") != null && !jsonObj.get("parent_version").isJsonNull()) && !jsonObj.get("parent_version").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `parent_version` to be a primitive type in the JSON string but got `%s`", jsonObj.get("parent_version").toString()));
      }
      if ((jsonObj.get("parent_author_url") != null && !jsonObj.get("parent_author_url").isJsonNull()) && !jsonObj.get("parent_author_url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `parent_author_url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("parent_author_url").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!WooCommerceSystemStatusTheme.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'WooCommerceSystemStatusTheme' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<WooCommerceSystemStatusTheme> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(WooCommerceSystemStatusTheme.class));

       return (TypeAdapter<T>) new TypeAdapter<WooCommerceSystemStatusTheme>() {
           @Override
           public void write(JsonWriter out, WooCommerceSystemStatusTheme value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public WooCommerceSystemStatusTheme read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             WooCommerceSystemStatusTheme instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of WooCommerceSystemStatusTheme given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of WooCommerceSystemStatusTheme
   * @throws IOException if the JSON string is invalid with respect to WooCommerceSystemStatusTheme
   */
  public static WooCommerceSystemStatusTheme fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, WooCommerceSystemStatusTheme.class);
  }

  /**
   * Convert an instance of WooCommerceSystemStatusTheme to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

