/*
 * Dev Store API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.9.1
 * Contact: admin@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.woocommerce.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.woocommerce.JSON;

/**
 * Shipping method settings.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.20.0-SNAPSHOT")
public class WooCommerceWcV3ShippingZonesZoneIdMethodsPostRequestSettings {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private String id;

  public static final String SERIALIZED_NAME_LABEL = "label";
  @SerializedName(SERIALIZED_NAME_LABEL)
  @javax.annotation.Nullable
  private String label;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  @javax.annotation.Nullable
  private String description;

  /**
   * Type of setting.
   */
  @JsonAdapter(TypeEnum.Adapter.class)
  public enum TypeEnum {
    TEXT("text"),
    
    EMAIL("email"),
    
    NUMBER("number"),
    
    COLOR("color"),
    
    PASSWORD("password"),
    
    TEXTAREA("textarea"),
    
    SELECT("select"),
    
    MULTISELECT("multiselect"),
    
    RADIO("radio"),
    
    IMAGE_WIDTH("image_width"),
    
    CHECKBOX("checkbox"),
    
    propertyClass("class"),
    
    ORDER("order"),
    
    UNKNOWN_DEFAULT_OPEN_API("unknown_default_open_api");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return UNKNOWN_DEFAULT_OPEN_API;
    }

    public static class Adapter extends TypeAdapter<TypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public TypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return TypeEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      TypeEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  @javax.annotation.Nullable
  private TypeEnum type;

  public static final String SERIALIZED_NAME_VALUE = "value";
  @SerializedName(SERIALIZED_NAME_VALUE)
  @javax.annotation.Nullable
  private String value;

  public static final String SERIALIZED_NAME_DEFAULT = "default";
  @SerializedName(SERIALIZED_NAME_DEFAULT)
  @javax.annotation.Nullable
  private String _default;

  public static final String SERIALIZED_NAME_TIP = "tip";
  @SerializedName(SERIALIZED_NAME_TIP)
  @javax.annotation.Nullable
  private String tip;

  public static final String SERIALIZED_NAME_PLACEHOLDER = "placeholder";
  @SerializedName(SERIALIZED_NAME_PLACEHOLDER)
  @javax.annotation.Nullable
  private String placeholder;

  public WooCommerceWcV3ShippingZonesZoneIdMethodsPostRequestSettings() {
  }

  public WooCommerceWcV3ShippingZonesZoneIdMethodsPostRequestSettings id(@javax.annotation.Nullable String id) {
    this.id = id;
    return this;
  }

  /**
   * A unique identifier for the setting.
   * @return id
   */
  @javax.annotation.Nullable
  public String getId() {
    return id;
  }

  public void setId(@javax.annotation.Nullable String id) {
    this.id = id;
  }


  public WooCommerceWcV3ShippingZonesZoneIdMethodsPostRequestSettings label(@javax.annotation.Nullable String label) {
    this.label = label;
    return this;
  }

  /**
   * A human readable label for the setting used in interfaces.
   * @return label
   */
  @javax.annotation.Nullable
  public String getLabel() {
    return label;
  }

  public void setLabel(@javax.annotation.Nullable String label) {
    this.label = label;
  }


  public WooCommerceWcV3ShippingZonesZoneIdMethodsPostRequestSettings description(@javax.annotation.Nullable String description) {
    this.description = description;
    return this;
  }

  /**
   * A human readable description for the setting used in interfaces.
   * @return description
   */
  @javax.annotation.Nullable
  public String getDescription() {
    return description;
  }

  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }


  public WooCommerceWcV3ShippingZonesZoneIdMethodsPostRequestSettings type(@javax.annotation.Nullable TypeEnum type) {
    this.type = type;
    return this;
  }

  /**
   * Type of setting.
   * @return type
   */
  @javax.annotation.Nullable
  public TypeEnum getType() {
    return type;
  }

  public void setType(@javax.annotation.Nullable TypeEnum type) {
    this.type = type;
  }


  public WooCommerceWcV3ShippingZonesZoneIdMethodsPostRequestSettings value(@javax.annotation.Nullable String value) {
    this.value = value;
    return this;
  }

  /**
   * Setting value.
   * @return value
   */
  @javax.annotation.Nullable
  public String getValue() {
    return value;
  }

  public void setValue(@javax.annotation.Nullable String value) {
    this.value = value;
  }


  public WooCommerceWcV3ShippingZonesZoneIdMethodsPostRequestSettings _default(@javax.annotation.Nullable String _default) {
    this._default = _default;
    return this;
  }

  /**
   * Default value for the setting.
   * @return _default
   */
  @javax.annotation.Nullable
  public String getDefault() {
    return _default;
  }

  public void setDefault(@javax.annotation.Nullable String _default) {
    this._default = _default;
  }


  public WooCommerceWcV3ShippingZonesZoneIdMethodsPostRequestSettings tip(@javax.annotation.Nullable String tip) {
    this.tip = tip;
    return this;
  }

  /**
   * Additional help text shown to the user about the setting.
   * @return tip
   */
  @javax.annotation.Nullable
  public String getTip() {
    return tip;
  }

  public void setTip(@javax.annotation.Nullable String tip) {
    this.tip = tip;
  }


  public WooCommerceWcV3ShippingZonesZoneIdMethodsPostRequestSettings placeholder(@javax.annotation.Nullable String placeholder) {
    this.placeholder = placeholder;
    return this;
  }

  /**
   * Placeholder text to be displayed in text inputs.
   * @return placeholder
   */
  @javax.annotation.Nullable
  public String getPlaceholder() {
    return placeholder;
  }

  public void setPlaceholder(@javax.annotation.Nullable String placeholder) {
    this.placeholder = placeholder;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the WooCommerceWcV3ShippingZonesZoneIdMethodsPostRequestSettings instance itself
   */
  public WooCommerceWcV3ShippingZonesZoneIdMethodsPostRequestSettings putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WooCommerceWcV3ShippingZonesZoneIdMethodsPostRequestSettings wcV3ShippingZonesZoneIdMethodsPostRequestSettings = (WooCommerceWcV3ShippingZonesZoneIdMethodsPostRequestSettings) o;
    return Objects.equals(this.id, wcV3ShippingZonesZoneIdMethodsPostRequestSettings.id) &&
        Objects.equals(this.label, wcV3ShippingZonesZoneIdMethodsPostRequestSettings.label) &&
        Objects.equals(this.description, wcV3ShippingZonesZoneIdMethodsPostRequestSettings.description) &&
        Objects.equals(this.type, wcV3ShippingZonesZoneIdMethodsPostRequestSettings.type) &&
        Objects.equals(this.value, wcV3ShippingZonesZoneIdMethodsPostRequestSettings.value) &&
        Objects.equals(this._default, wcV3ShippingZonesZoneIdMethodsPostRequestSettings._default) &&
        Objects.equals(this.tip, wcV3ShippingZonesZoneIdMethodsPostRequestSettings.tip) &&
        Objects.equals(this.placeholder, wcV3ShippingZonesZoneIdMethodsPostRequestSettings.placeholder)&&
        Objects.equals(this.additionalProperties, wcV3ShippingZonesZoneIdMethodsPostRequestSettings.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, label, description, type, value, _default, tip, placeholder, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WooCommerceWcV3ShippingZonesZoneIdMethodsPostRequestSettings {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    _default: ").append(toIndentedString(_default)).append("\n");
    sb.append("    tip: ").append(toIndentedString(tip)).append("\n");
    sb.append("    placeholder: ").append(toIndentedString(placeholder)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("id", "label", "description", "type", "value", "default", "tip", "placeholder"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to WooCommerceWcV3ShippingZonesZoneIdMethodsPostRequestSettings
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!WooCommerceWcV3ShippingZonesZoneIdMethodsPostRequestSettings.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in WooCommerceWcV3ShippingZonesZoneIdMethodsPostRequestSettings is not found in the empty JSON string", WooCommerceWcV3ShippingZonesZoneIdMethodsPostRequestSettings.openapiRequiredFields.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if ((jsonObj.get("label") != null && !jsonObj.get("label").isJsonNull()) && !jsonObj.get("label").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `label` to be a primitive type in the JSON string but got `%s`", jsonObj.get("label").toString()));
      }
      if ((jsonObj.get("description") != null && !jsonObj.get("description").isJsonNull()) && !jsonObj.get("description").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `description` to be a primitive type in the JSON string but got `%s`", jsonObj.get("description").toString()));
      }
      if ((jsonObj.get("type") != null && !jsonObj.get("type").isJsonNull()) && !jsonObj.get("type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("type").toString()));
      }
      // validate the optional field `type`
      if (jsonObj.get("type") != null && !jsonObj.get("type").isJsonNull()) {
        TypeEnum.validateJsonElement(jsonObj.get("type"));
      }
      if ((jsonObj.get("value") != null && !jsonObj.get("value").isJsonNull()) && !jsonObj.get("value").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `value` to be a primitive type in the JSON string but got `%s`", jsonObj.get("value").toString()));
      }
      if ((jsonObj.get("default") != null && !jsonObj.get("default").isJsonNull()) && !jsonObj.get("default").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `default` to be a primitive type in the JSON string but got `%s`", jsonObj.get("default").toString()));
      }
      if ((jsonObj.get("tip") != null && !jsonObj.get("tip").isJsonNull()) && !jsonObj.get("tip").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `tip` to be a primitive type in the JSON string but got `%s`", jsonObj.get("tip").toString()));
      }
      if ((jsonObj.get("placeholder") != null && !jsonObj.get("placeholder").isJsonNull()) && !jsonObj.get("placeholder").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `placeholder` to be a primitive type in the JSON string but got `%s`", jsonObj.get("placeholder").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!WooCommerceWcV3ShippingZonesZoneIdMethodsPostRequestSettings.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'WooCommerceWcV3ShippingZonesZoneIdMethodsPostRequestSettings' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<WooCommerceWcV3ShippingZonesZoneIdMethodsPostRequestSettings> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(WooCommerceWcV3ShippingZonesZoneIdMethodsPostRequestSettings.class));

       return (TypeAdapter<T>) new TypeAdapter<WooCommerceWcV3ShippingZonesZoneIdMethodsPostRequestSettings>() {
           @Override
           public void write(JsonWriter out, WooCommerceWcV3ShippingZonesZoneIdMethodsPostRequestSettings value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public WooCommerceWcV3ShippingZonesZoneIdMethodsPostRequestSettings read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             WooCommerceWcV3ShippingZonesZoneIdMethodsPostRequestSettings instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of WooCommerceWcV3ShippingZonesZoneIdMethodsPostRequestSettings given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of WooCommerceWcV3ShippingZonesZoneIdMethodsPostRequestSettings
   * @throws IOException if the JSON string is invalid with respect to WooCommerceWcV3ShippingZonesZoneIdMethodsPostRequestSettings
   */
  public static WooCommerceWcV3ShippingZonesZoneIdMethodsPostRequestSettings fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, WooCommerceWcV3ShippingZonesZoneIdMethodsPostRequestSettings.class);
  }

  /**
   * Convert an instance of WooCommerceWcV3ShippingZonesZoneIdMethodsPostRequestSettings to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

