/*
 * Dev Store API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.9.1
 * Contact: admin@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.woocommerce.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.woocommerce.model.WooCommerceCustomerDownloadFile;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.woocommerce.JSON;

/**
 * WooCommerceCustomerDownload
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.20.0-SNAPSHOT")
public class WooCommerceCustomerDownload {
  public static final String SERIALIZED_NAME_DOWNLOAD_ID = "download_id";
  @SerializedName(SERIALIZED_NAME_DOWNLOAD_ID)
  @javax.annotation.Nullable
  private String downloadId;

  public static final String SERIALIZED_NAME_DOWNLOAD_URL = "download_url";
  @SerializedName(SERIALIZED_NAME_DOWNLOAD_URL)
  @javax.annotation.Nullable
  private String downloadUrl;

  public static final String SERIALIZED_NAME_PRODUCT_ID = "product_id";
  @SerializedName(SERIALIZED_NAME_PRODUCT_ID)
  @javax.annotation.Nullable
  private Integer productId;

  public static final String SERIALIZED_NAME_PRODUCT_NAME = "product_name";
  @SerializedName(SERIALIZED_NAME_PRODUCT_NAME)
  @javax.annotation.Nullable
  private String productName;

  public static final String SERIALIZED_NAME_DOWNLOAD_NAME = "download_name";
  @SerializedName(SERIALIZED_NAME_DOWNLOAD_NAME)
  @javax.annotation.Nullable
  private String downloadName;

  public static final String SERIALIZED_NAME_ORDER_ID = "order_id";
  @SerializedName(SERIALIZED_NAME_ORDER_ID)
  @javax.annotation.Nullable
  private Integer orderId;

  public static final String SERIALIZED_NAME_ORDER_KEY = "order_key";
  @SerializedName(SERIALIZED_NAME_ORDER_KEY)
  @javax.annotation.Nullable
  private String orderKey;

  public static final String SERIALIZED_NAME_DOWNLOADS_REMAINING = "downloads_remaining";
  @SerializedName(SERIALIZED_NAME_DOWNLOADS_REMAINING)
  @javax.annotation.Nullable
  private String downloadsRemaining;

  public static final String SERIALIZED_NAME_ACCESS_EXPIRES = "access_expires";
  @SerializedName(SERIALIZED_NAME_ACCESS_EXPIRES)
  @javax.annotation.Nullable
  private String accessExpires;

  public static final String SERIALIZED_NAME_ACCESS_EXPIRES_GMT = "access_expires_gmt";
  @SerializedName(SERIALIZED_NAME_ACCESS_EXPIRES_GMT)
  @javax.annotation.Nullable
  private String accessExpiresGmt;

  public static final String SERIALIZED_NAME_FILE = "file";
  @SerializedName(SERIALIZED_NAME_FILE)
  @javax.annotation.Nullable
  private WooCommerceCustomerDownloadFile _file;

  public WooCommerceCustomerDownload() {
  }

  public WooCommerceCustomerDownload downloadId(@javax.annotation.Nullable String downloadId) {
    this.downloadId = downloadId;
    return this;
  }

  /**
   * Download ID.
   * @return downloadId
   */
  @javax.annotation.Nullable
  public String getDownloadId() {
    return downloadId;
  }

  public void setDownloadId(@javax.annotation.Nullable String downloadId) {
    this.downloadId = downloadId;
  }


  public WooCommerceCustomerDownload downloadUrl(@javax.annotation.Nullable String downloadUrl) {
    this.downloadUrl = downloadUrl;
    return this;
  }

  /**
   * Download file URL.
   * @return downloadUrl
   */
  @javax.annotation.Nullable
  public String getDownloadUrl() {
    return downloadUrl;
  }

  public void setDownloadUrl(@javax.annotation.Nullable String downloadUrl) {
    this.downloadUrl = downloadUrl;
  }


  public WooCommerceCustomerDownload productId(@javax.annotation.Nullable Integer productId) {
    this.productId = productId;
    return this;
  }

  /**
   * Downloadable product ID.
   * @return productId
   */
  @javax.annotation.Nullable
  public Integer getProductId() {
    return productId;
  }

  public void setProductId(@javax.annotation.Nullable Integer productId) {
    this.productId = productId;
  }


  public WooCommerceCustomerDownload productName(@javax.annotation.Nullable String productName) {
    this.productName = productName;
    return this;
  }

  /**
   * Product name.
   * @return productName
   */
  @javax.annotation.Nullable
  public String getProductName() {
    return productName;
  }

  public void setProductName(@javax.annotation.Nullable String productName) {
    this.productName = productName;
  }


  public WooCommerceCustomerDownload downloadName(@javax.annotation.Nullable String downloadName) {
    this.downloadName = downloadName;
    return this;
  }

  /**
   * Downloadable file name.
   * @return downloadName
   */
  @javax.annotation.Nullable
  public String getDownloadName() {
    return downloadName;
  }

  public void setDownloadName(@javax.annotation.Nullable String downloadName) {
    this.downloadName = downloadName;
  }


  public WooCommerceCustomerDownload orderId(@javax.annotation.Nullable Integer orderId) {
    this.orderId = orderId;
    return this;
  }

  /**
   * Order ID.
   * @return orderId
   */
  @javax.annotation.Nullable
  public Integer getOrderId() {
    return orderId;
  }

  public void setOrderId(@javax.annotation.Nullable Integer orderId) {
    this.orderId = orderId;
  }


  public WooCommerceCustomerDownload orderKey(@javax.annotation.Nullable String orderKey) {
    this.orderKey = orderKey;
    return this;
  }

  /**
   * Order key.
   * @return orderKey
   */
  @javax.annotation.Nullable
  public String getOrderKey() {
    return orderKey;
  }

  public void setOrderKey(@javax.annotation.Nullable String orderKey) {
    this.orderKey = orderKey;
  }


  public WooCommerceCustomerDownload downloadsRemaining(@javax.annotation.Nullable String downloadsRemaining) {
    this.downloadsRemaining = downloadsRemaining;
    return this;
  }

  /**
   * Number of downloads remaining.
   * @return downloadsRemaining
   */
  @javax.annotation.Nullable
  public String getDownloadsRemaining() {
    return downloadsRemaining;
  }

  public void setDownloadsRemaining(@javax.annotation.Nullable String downloadsRemaining) {
    this.downloadsRemaining = downloadsRemaining;
  }


  public WooCommerceCustomerDownload accessExpires(@javax.annotation.Nullable String accessExpires) {
    this.accessExpires = accessExpires;
    return this;
  }

  /**
   * The date when download access expires, in the site&#39;s timezone.
   * @return accessExpires
   */
  @javax.annotation.Nullable
  public String getAccessExpires() {
    return accessExpires;
  }

  public void setAccessExpires(@javax.annotation.Nullable String accessExpires) {
    this.accessExpires = accessExpires;
  }


  public WooCommerceCustomerDownload accessExpiresGmt(@javax.annotation.Nullable String accessExpiresGmt) {
    this.accessExpiresGmt = accessExpiresGmt;
    return this;
  }

  /**
   * The date when download access expires, as GMT.
   * @return accessExpiresGmt
   */
  @javax.annotation.Nullable
  public String getAccessExpiresGmt() {
    return accessExpiresGmt;
  }

  public void setAccessExpiresGmt(@javax.annotation.Nullable String accessExpiresGmt) {
    this.accessExpiresGmt = accessExpiresGmt;
  }


  public WooCommerceCustomerDownload _file(@javax.annotation.Nullable WooCommerceCustomerDownloadFile _file) {
    this._file = _file;
    return this;
  }

  /**
   * Get _file
   * @return _file
   */
  @javax.annotation.Nullable
  public WooCommerceCustomerDownloadFile getFile() {
    return _file;
  }

  public void setFile(@javax.annotation.Nullable WooCommerceCustomerDownloadFile _file) {
    this._file = _file;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the WooCommerceCustomerDownload instance itself
   */
  public WooCommerceCustomerDownload putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WooCommerceCustomerDownload customerDownload = (WooCommerceCustomerDownload) o;
    return Objects.equals(this.downloadId, customerDownload.downloadId) &&
        Objects.equals(this.downloadUrl, customerDownload.downloadUrl) &&
        Objects.equals(this.productId, customerDownload.productId) &&
        Objects.equals(this.productName, customerDownload.productName) &&
        Objects.equals(this.downloadName, customerDownload.downloadName) &&
        Objects.equals(this.orderId, customerDownload.orderId) &&
        Objects.equals(this.orderKey, customerDownload.orderKey) &&
        Objects.equals(this.downloadsRemaining, customerDownload.downloadsRemaining) &&
        Objects.equals(this.accessExpires, customerDownload.accessExpires) &&
        Objects.equals(this.accessExpiresGmt, customerDownload.accessExpiresGmt) &&
        Objects.equals(this._file, customerDownload._file)&&
        Objects.equals(this.additionalProperties, customerDownload.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(downloadId, downloadUrl, productId, productName, downloadName, orderId, orderKey, downloadsRemaining, accessExpires, accessExpiresGmt, _file, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WooCommerceCustomerDownload {\n");
    sb.append("    downloadId: ").append(toIndentedString(downloadId)).append("\n");
    sb.append("    downloadUrl: ").append(toIndentedString(downloadUrl)).append("\n");
    sb.append("    productId: ").append(toIndentedString(productId)).append("\n");
    sb.append("    productName: ").append(toIndentedString(productName)).append("\n");
    sb.append("    downloadName: ").append(toIndentedString(downloadName)).append("\n");
    sb.append("    orderId: ").append(toIndentedString(orderId)).append("\n");
    sb.append("    orderKey: ").append(toIndentedString(orderKey)).append("\n");
    sb.append("    downloadsRemaining: ").append(toIndentedString(downloadsRemaining)).append("\n");
    sb.append("    accessExpires: ").append(toIndentedString(accessExpires)).append("\n");
    sb.append("    accessExpiresGmt: ").append(toIndentedString(accessExpiresGmt)).append("\n");
    sb.append("    _file: ").append(toIndentedString(_file)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("download_id", "download_url", "product_id", "product_name", "download_name", "order_id", "order_key", "downloads_remaining", "access_expires", "access_expires_gmt", "file"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to WooCommerceCustomerDownload
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!WooCommerceCustomerDownload.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in WooCommerceCustomerDownload is not found in the empty JSON string", WooCommerceCustomerDownload.openapiRequiredFields.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("download_id") != null && !jsonObj.get("download_id").isJsonNull()) && !jsonObj.get("download_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `download_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("download_id").toString()));
      }
      if ((jsonObj.get("download_url") != null && !jsonObj.get("download_url").isJsonNull()) && !jsonObj.get("download_url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `download_url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("download_url").toString()));
      }
      if ((jsonObj.get("product_name") != null && !jsonObj.get("product_name").isJsonNull()) && !jsonObj.get("product_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `product_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("product_name").toString()));
      }
      if ((jsonObj.get("download_name") != null && !jsonObj.get("download_name").isJsonNull()) && !jsonObj.get("download_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `download_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("download_name").toString()));
      }
      if ((jsonObj.get("order_key") != null && !jsonObj.get("order_key").isJsonNull()) && !jsonObj.get("order_key").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `order_key` to be a primitive type in the JSON string but got `%s`", jsonObj.get("order_key").toString()));
      }
      if ((jsonObj.get("downloads_remaining") != null && !jsonObj.get("downloads_remaining").isJsonNull()) && !jsonObj.get("downloads_remaining").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `downloads_remaining` to be a primitive type in the JSON string but got `%s`", jsonObj.get("downloads_remaining").toString()));
      }
      if ((jsonObj.get("access_expires") != null && !jsonObj.get("access_expires").isJsonNull()) && !jsonObj.get("access_expires").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `access_expires` to be a primitive type in the JSON string but got `%s`", jsonObj.get("access_expires").toString()));
      }
      if ((jsonObj.get("access_expires_gmt") != null && !jsonObj.get("access_expires_gmt").isJsonNull()) && !jsonObj.get("access_expires_gmt").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `access_expires_gmt` to be a primitive type in the JSON string but got `%s`", jsonObj.get("access_expires_gmt").toString()));
      }
      // validate the optional field `file`
      if (jsonObj.get("file") != null && !jsonObj.get("file").isJsonNull()) {
        WooCommerceCustomerDownloadFile.validateJsonElement(jsonObj.get("file"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!WooCommerceCustomerDownload.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'WooCommerceCustomerDownload' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<WooCommerceCustomerDownload> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(WooCommerceCustomerDownload.class));

       return (TypeAdapter<T>) new TypeAdapter<WooCommerceCustomerDownload>() {
           @Override
           public void write(JsonWriter out, WooCommerceCustomerDownload value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public WooCommerceCustomerDownload read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             WooCommerceCustomerDownload instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of WooCommerceCustomerDownload given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of WooCommerceCustomerDownload
   * @throws IOException if the JSON string is invalid with respect to WooCommerceCustomerDownload
   */
  public static WooCommerceCustomerDownload fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, WooCommerceCustomerDownload.class);
  }

  /**
   * Convert an instance of WooCommerceCustomerDownload to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

