/*
 * Dev Store API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.9.1
 * Contact: admin@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.woocommerce.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.woocommerce.model.WooCommerceShopCouponMetaDataInner;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.woocommerce.JSON;

/**
 * WooCommerceShopOrderRefundTaxLinesInner
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.20.0-SNAPSHOT")
public class WooCommerceShopOrderRefundTaxLinesInner {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private Integer id;

  public static final String SERIALIZED_NAME_RATE_CODE = "rate_code";
  @SerializedName(SERIALIZED_NAME_RATE_CODE)
  @javax.annotation.Nullable
  private String rateCode;

  public static final String SERIALIZED_NAME_RATE_ID = "rate_id";
  @SerializedName(SERIALIZED_NAME_RATE_ID)
  @javax.annotation.Nullable
  private Integer rateId;

  public static final String SERIALIZED_NAME_LABEL = "label";
  @SerializedName(SERIALIZED_NAME_LABEL)
  @javax.annotation.Nullable
  private String label;

  public static final String SERIALIZED_NAME_COMPOUND = "compound";
  @SerializedName(SERIALIZED_NAME_COMPOUND)
  @javax.annotation.Nullable
  private Boolean compound;

  public static final String SERIALIZED_NAME_TAX_TOTAL = "tax_total";
  @SerializedName(SERIALIZED_NAME_TAX_TOTAL)
  @javax.annotation.Nullable
  private String taxTotal;

  public static final String SERIALIZED_NAME_SHIPPING_TAX_TOTAL = "shipping_tax_total";
  @SerializedName(SERIALIZED_NAME_SHIPPING_TAX_TOTAL)
  @javax.annotation.Nullable
  private String shippingTaxTotal;

  public static final String SERIALIZED_NAME_META_DATA = "meta_data";
  @SerializedName(SERIALIZED_NAME_META_DATA)
  @javax.annotation.Nullable
  private List<WooCommerceShopCouponMetaDataInner> metaData = new ArrayList<>();

  public WooCommerceShopOrderRefundTaxLinesInner() {
  }

  public WooCommerceShopOrderRefundTaxLinesInner id(@javax.annotation.Nullable Integer id) {
    this.id = id;
    return this;
  }

  /**
   * Item ID.
   * @return id
   */
  @javax.annotation.Nullable
  public Integer getId() {
    return id;
  }

  public void setId(@javax.annotation.Nullable Integer id) {
    this.id = id;
  }


  public WooCommerceShopOrderRefundTaxLinesInner rateCode(@javax.annotation.Nullable String rateCode) {
    this.rateCode = rateCode;
    return this;
  }

  /**
   * Tax rate code.
   * @return rateCode
   */
  @javax.annotation.Nullable
  public String getRateCode() {
    return rateCode;
  }

  public void setRateCode(@javax.annotation.Nullable String rateCode) {
    this.rateCode = rateCode;
  }


  public WooCommerceShopOrderRefundTaxLinesInner rateId(@javax.annotation.Nullable Integer rateId) {
    this.rateId = rateId;
    return this;
  }

  /**
   * Tax rate ID.
   * @return rateId
   */
  @javax.annotation.Nullable
  public Integer getRateId() {
    return rateId;
  }

  public void setRateId(@javax.annotation.Nullable Integer rateId) {
    this.rateId = rateId;
  }


  public WooCommerceShopOrderRefundTaxLinesInner label(@javax.annotation.Nullable String label) {
    this.label = label;
    return this;
  }

  /**
   * Tax rate label.
   * @return label
   */
  @javax.annotation.Nullable
  public String getLabel() {
    return label;
  }

  public void setLabel(@javax.annotation.Nullable String label) {
    this.label = label;
  }


  public WooCommerceShopOrderRefundTaxLinesInner compound(@javax.annotation.Nullable Boolean compound) {
    this.compound = compound;
    return this;
  }

  /**
   * Show if is a compound tax rate.
   * @return compound
   */
  @javax.annotation.Nullable
  public Boolean getCompound() {
    return compound;
  }

  public void setCompound(@javax.annotation.Nullable Boolean compound) {
    this.compound = compound;
  }


  public WooCommerceShopOrderRefundTaxLinesInner taxTotal(@javax.annotation.Nullable String taxTotal) {
    this.taxTotal = taxTotal;
    return this;
  }

  /**
   * Tax total (not including shipping taxes).
   * @return taxTotal
   */
  @javax.annotation.Nullable
  public String getTaxTotal() {
    return taxTotal;
  }

  public void setTaxTotal(@javax.annotation.Nullable String taxTotal) {
    this.taxTotal = taxTotal;
  }


  public WooCommerceShopOrderRefundTaxLinesInner shippingTaxTotal(@javax.annotation.Nullable String shippingTaxTotal) {
    this.shippingTaxTotal = shippingTaxTotal;
    return this;
  }

  /**
   * Shipping tax total.
   * @return shippingTaxTotal
   */
  @javax.annotation.Nullable
  public String getShippingTaxTotal() {
    return shippingTaxTotal;
  }

  public void setShippingTaxTotal(@javax.annotation.Nullable String shippingTaxTotal) {
    this.shippingTaxTotal = shippingTaxTotal;
  }


  public WooCommerceShopOrderRefundTaxLinesInner metaData(@javax.annotation.Nullable List<WooCommerceShopCouponMetaDataInner> metaData) {
    this.metaData = metaData;
    return this;
  }

  public WooCommerceShopOrderRefundTaxLinesInner addMetaDataItem(WooCommerceShopCouponMetaDataInner metaDataItem) {
    if (this.metaData == null) {
      this.metaData = new ArrayList<>();
    }
    this.metaData.add(metaDataItem);
    return this;
  }

  /**
   * Meta data.
   * @return metaData
   */
  @javax.annotation.Nullable
  public List<WooCommerceShopCouponMetaDataInner> getMetaData() {
    return metaData;
  }

  public void setMetaData(@javax.annotation.Nullable List<WooCommerceShopCouponMetaDataInner> metaData) {
    this.metaData = metaData;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the WooCommerceShopOrderRefundTaxLinesInner instance itself
   */
  public WooCommerceShopOrderRefundTaxLinesInner putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WooCommerceShopOrderRefundTaxLinesInner shopOrderRefundTaxLinesInner = (WooCommerceShopOrderRefundTaxLinesInner) o;
    return Objects.equals(this.id, shopOrderRefundTaxLinesInner.id) &&
        Objects.equals(this.rateCode, shopOrderRefundTaxLinesInner.rateCode) &&
        Objects.equals(this.rateId, shopOrderRefundTaxLinesInner.rateId) &&
        Objects.equals(this.label, shopOrderRefundTaxLinesInner.label) &&
        Objects.equals(this.compound, shopOrderRefundTaxLinesInner.compound) &&
        Objects.equals(this.taxTotal, shopOrderRefundTaxLinesInner.taxTotal) &&
        Objects.equals(this.shippingTaxTotal, shopOrderRefundTaxLinesInner.shippingTaxTotal) &&
        Objects.equals(this.metaData, shopOrderRefundTaxLinesInner.metaData)&&
        Objects.equals(this.additionalProperties, shopOrderRefundTaxLinesInner.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, rateCode, rateId, label, compound, taxTotal, shippingTaxTotal, metaData, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WooCommerceShopOrderRefundTaxLinesInner {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    rateCode: ").append(toIndentedString(rateCode)).append("\n");
    sb.append("    rateId: ").append(toIndentedString(rateId)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    compound: ").append(toIndentedString(compound)).append("\n");
    sb.append("    taxTotal: ").append(toIndentedString(taxTotal)).append("\n");
    sb.append("    shippingTaxTotal: ").append(toIndentedString(shippingTaxTotal)).append("\n");
    sb.append("    metaData: ").append(toIndentedString(metaData)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("id", "rate_code", "rate_id", "label", "compound", "tax_total", "shipping_tax_total", "meta_data"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to WooCommerceShopOrderRefundTaxLinesInner
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!WooCommerceShopOrderRefundTaxLinesInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in WooCommerceShopOrderRefundTaxLinesInner is not found in the empty JSON string", WooCommerceShopOrderRefundTaxLinesInner.openapiRequiredFields.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("rate_code") != null && !jsonObj.get("rate_code").isJsonNull()) && !jsonObj.get("rate_code").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `rate_code` to be a primitive type in the JSON string but got `%s`", jsonObj.get("rate_code").toString()));
      }
      if ((jsonObj.get("label") != null && !jsonObj.get("label").isJsonNull()) && !jsonObj.get("label").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `label` to be a primitive type in the JSON string but got `%s`", jsonObj.get("label").toString()));
      }
      if ((jsonObj.get("tax_total") != null && !jsonObj.get("tax_total").isJsonNull()) && !jsonObj.get("tax_total").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `tax_total` to be a primitive type in the JSON string but got `%s`", jsonObj.get("tax_total").toString()));
      }
      if ((jsonObj.get("shipping_tax_total") != null && !jsonObj.get("shipping_tax_total").isJsonNull()) && !jsonObj.get("shipping_tax_total").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `shipping_tax_total` to be a primitive type in the JSON string but got `%s`", jsonObj.get("shipping_tax_total").toString()));
      }
      if (jsonObj.get("meta_data") != null && !jsonObj.get("meta_data").isJsonNull()) {
        JsonArray jsonArraymetaData = jsonObj.getAsJsonArray("meta_data");
        if (jsonArraymetaData != null) {
          // ensure the json data is an array
          if (!jsonObj.get("meta_data").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `meta_data` to be an array in the JSON string but got `%s`", jsonObj.get("meta_data").toString()));
          }

          // validate the optional field `meta_data` (array)
          for (int i = 0; i < jsonArraymetaData.size(); i++) {
            WooCommerceShopCouponMetaDataInner.validateJsonElement(jsonArraymetaData.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!WooCommerceShopOrderRefundTaxLinesInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'WooCommerceShopOrderRefundTaxLinesInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<WooCommerceShopOrderRefundTaxLinesInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(WooCommerceShopOrderRefundTaxLinesInner.class));

       return (TypeAdapter<T>) new TypeAdapter<WooCommerceShopOrderRefundTaxLinesInner>() {
           @Override
           public void write(JsonWriter out, WooCommerceShopOrderRefundTaxLinesInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public WooCommerceShopOrderRefundTaxLinesInner read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             WooCommerceShopOrderRefundTaxLinesInner instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of WooCommerceShopOrderRefundTaxLinesInner given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of WooCommerceShopOrderRefundTaxLinesInner
   * @throws IOException if the JSON string is invalid with respect to WooCommerceShopOrderRefundTaxLinesInner
   */
  public static WooCommerceShopOrderRefundTaxLinesInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, WooCommerceShopOrderRefundTaxLinesInner.class);
  }

  /**
   * Convert an instance of WooCommerceShopOrderRefundTaxLinesInner to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

