/*
 * Dev Store API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.9.1
 * Contact: admin@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.woocommerce.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.woocommerce.model.WooCommerceWcV3PaymentGatewaysIdPutRequestSettings;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.woocommerce.JSON;

/**
 * WooCommercePaymentGateway
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.20.0-SNAPSHOT")
public class WooCommercePaymentGateway {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private String id;

  public static final String SERIALIZED_NAME_TITLE = "title";
  @SerializedName(SERIALIZED_NAME_TITLE)
  @javax.annotation.Nullable
  private String title;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  @javax.annotation.Nullable
  private String description;

  public static final String SERIALIZED_NAME_ORDER = "order";
  @SerializedName(SERIALIZED_NAME_ORDER)
  @javax.annotation.Nullable
  private Integer order;

  public static final String SERIALIZED_NAME_ENABLED = "enabled";
  @SerializedName(SERIALIZED_NAME_ENABLED)
  @javax.annotation.Nullable
  private Boolean enabled;

  public static final String SERIALIZED_NAME_METHOD_TITLE = "method_title";
  @SerializedName(SERIALIZED_NAME_METHOD_TITLE)
  @javax.annotation.Nullable
  private String methodTitle;

  public static final String SERIALIZED_NAME_METHOD_DESCRIPTION = "method_description";
  @SerializedName(SERIALIZED_NAME_METHOD_DESCRIPTION)
  @javax.annotation.Nullable
  private String methodDescription;

  public static final String SERIALIZED_NAME_METHOD_SUPPORTS = "method_supports";
  @SerializedName(SERIALIZED_NAME_METHOD_SUPPORTS)
  @javax.annotation.Nullable
  private List<String> methodSupports = new ArrayList<>();

  public static final String SERIALIZED_NAME_SETTINGS = "settings";
  @SerializedName(SERIALIZED_NAME_SETTINGS)
  @javax.annotation.Nullable
  private WooCommerceWcV3PaymentGatewaysIdPutRequestSettings settings;

  public WooCommercePaymentGateway() {
  }

  public WooCommercePaymentGateway id(@javax.annotation.Nullable String id) {
    this.id = id;
    return this;
  }

  /**
   * Payment gateway ID.
   * @return id
   */
  @javax.annotation.Nullable
  public String getId() {
    return id;
  }

  public void setId(@javax.annotation.Nullable String id) {
    this.id = id;
  }


  public WooCommercePaymentGateway title(@javax.annotation.Nullable String title) {
    this.title = title;
    return this;
  }

  /**
   * Payment gateway title on checkout.
   * @return title
   */
  @javax.annotation.Nullable
  public String getTitle() {
    return title;
  }

  public void setTitle(@javax.annotation.Nullable String title) {
    this.title = title;
  }


  public WooCommercePaymentGateway description(@javax.annotation.Nullable String description) {
    this.description = description;
    return this;
  }

  /**
   * Payment gateway description on checkout.
   * @return description
   */
  @javax.annotation.Nullable
  public String getDescription() {
    return description;
  }

  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }


  public WooCommercePaymentGateway order(@javax.annotation.Nullable Integer order) {
    this.order = order;
    return this;
  }

  /**
   * Payment gateway sort order.
   * @return order
   */
  @javax.annotation.Nullable
  public Integer getOrder() {
    return order;
  }

  public void setOrder(@javax.annotation.Nullable Integer order) {
    this.order = order;
  }


  public WooCommercePaymentGateway enabled(@javax.annotation.Nullable Boolean enabled) {
    this.enabled = enabled;
    return this;
  }

  /**
   * Payment gateway enabled status.
   * @return enabled
   */
  @javax.annotation.Nullable
  public Boolean getEnabled() {
    return enabled;
  }

  public void setEnabled(@javax.annotation.Nullable Boolean enabled) {
    this.enabled = enabled;
  }


  public WooCommercePaymentGateway methodTitle(@javax.annotation.Nullable String methodTitle) {
    this.methodTitle = methodTitle;
    return this;
  }

  /**
   * Payment gateway method title.
   * @return methodTitle
   */
  @javax.annotation.Nullable
  public String getMethodTitle() {
    return methodTitle;
  }

  public void setMethodTitle(@javax.annotation.Nullable String methodTitle) {
    this.methodTitle = methodTitle;
  }


  public WooCommercePaymentGateway methodDescription(@javax.annotation.Nullable String methodDescription) {
    this.methodDescription = methodDescription;
    return this;
  }

  /**
   * Payment gateway method description.
   * @return methodDescription
   */
  @javax.annotation.Nullable
  public String getMethodDescription() {
    return methodDescription;
  }

  public void setMethodDescription(@javax.annotation.Nullable String methodDescription) {
    this.methodDescription = methodDescription;
  }


  public WooCommercePaymentGateway methodSupports(@javax.annotation.Nullable List<String> methodSupports) {
    this.methodSupports = methodSupports;
    return this;
  }

  public WooCommercePaymentGateway addMethodSupportsItem(String methodSupportsItem) {
    if (this.methodSupports == null) {
      this.methodSupports = new ArrayList<>();
    }
    this.methodSupports.add(methodSupportsItem);
    return this;
  }

  /**
   * Supported features for this payment gateway.
   * @return methodSupports
   */
  @javax.annotation.Nullable
  public List<String> getMethodSupports() {
    return methodSupports;
  }

  public void setMethodSupports(@javax.annotation.Nullable List<String> methodSupports) {
    this.methodSupports = methodSupports;
  }


  public WooCommercePaymentGateway settings(@javax.annotation.Nullable WooCommerceWcV3PaymentGatewaysIdPutRequestSettings settings) {
    this.settings = settings;
    return this;
  }

  /**
   * Get settings
   * @return settings
   */
  @javax.annotation.Nullable
  public WooCommerceWcV3PaymentGatewaysIdPutRequestSettings getSettings() {
    return settings;
  }

  public void setSettings(@javax.annotation.Nullable WooCommerceWcV3PaymentGatewaysIdPutRequestSettings settings) {
    this.settings = settings;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the WooCommercePaymentGateway instance itself
   */
  public WooCommercePaymentGateway putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WooCommercePaymentGateway paymentGateway = (WooCommercePaymentGateway) o;
    return Objects.equals(this.id, paymentGateway.id) &&
        Objects.equals(this.title, paymentGateway.title) &&
        Objects.equals(this.description, paymentGateway.description) &&
        Objects.equals(this.order, paymentGateway.order) &&
        Objects.equals(this.enabled, paymentGateway.enabled) &&
        Objects.equals(this.methodTitle, paymentGateway.methodTitle) &&
        Objects.equals(this.methodDescription, paymentGateway.methodDescription) &&
        Objects.equals(this.methodSupports, paymentGateway.methodSupports) &&
        Objects.equals(this.settings, paymentGateway.settings)&&
        Objects.equals(this.additionalProperties, paymentGateway.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, title, description, order, enabled, methodTitle, methodDescription, methodSupports, settings, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WooCommercePaymentGateway {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    order: ").append(toIndentedString(order)).append("\n");
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("    methodTitle: ").append(toIndentedString(methodTitle)).append("\n");
    sb.append("    methodDescription: ").append(toIndentedString(methodDescription)).append("\n");
    sb.append("    methodSupports: ").append(toIndentedString(methodSupports)).append("\n");
    sb.append("    settings: ").append(toIndentedString(settings)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("id", "title", "description", "order", "enabled", "method_title", "method_description", "method_supports", "settings"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to WooCommercePaymentGateway
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!WooCommercePaymentGateway.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in WooCommercePaymentGateway is not found in the empty JSON string", WooCommercePaymentGateway.openapiRequiredFields.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if ((jsonObj.get("title") != null && !jsonObj.get("title").isJsonNull()) && !jsonObj.get("title").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `title` to be a primitive type in the JSON string but got `%s`", jsonObj.get("title").toString()));
      }
      if ((jsonObj.get("description") != null && !jsonObj.get("description").isJsonNull()) && !jsonObj.get("description").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `description` to be a primitive type in the JSON string but got `%s`", jsonObj.get("description").toString()));
      }
      if ((jsonObj.get("method_title") != null && !jsonObj.get("method_title").isJsonNull()) && !jsonObj.get("method_title").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `method_title` to be a primitive type in the JSON string but got `%s`", jsonObj.get("method_title").toString()));
      }
      if ((jsonObj.get("method_description") != null && !jsonObj.get("method_description").isJsonNull()) && !jsonObj.get("method_description").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `method_description` to be a primitive type in the JSON string but got `%s`", jsonObj.get("method_description").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("method_supports") != null && !jsonObj.get("method_supports").isJsonNull() && !jsonObj.get("method_supports").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `method_supports` to be an array in the JSON string but got `%s`", jsonObj.get("method_supports").toString()));
      }
      // validate the optional field `settings`
      if (jsonObj.get("settings") != null && !jsonObj.get("settings").isJsonNull()) {
        WooCommerceWcV3PaymentGatewaysIdPutRequestSettings.validateJsonElement(jsonObj.get("settings"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!WooCommercePaymentGateway.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'WooCommercePaymentGateway' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<WooCommercePaymentGateway> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(WooCommercePaymentGateway.class));

       return (TypeAdapter<T>) new TypeAdapter<WooCommercePaymentGateway>() {
           @Override
           public void write(JsonWriter out, WooCommercePaymentGateway value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public WooCommercePaymentGateway read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             WooCommercePaymentGateway instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of WooCommercePaymentGateway given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of WooCommercePaymentGateway
   * @throws IOException if the JSON string is invalid with respect to WooCommercePaymentGateway
   */
  public static WooCommercePaymentGateway fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, WooCommercePaymentGateway.class);
  }

  /**
   * Convert an instance of WooCommercePaymentGateway to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

