/*
 * Dev Store API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.9.1
 * Contact: admin@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.woocommerce.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.woocommerce.model.WooCommerceWcV3ShippingZonesZoneIdMethodsPostRequestSettings;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.woocommerce.JSON;

/**
 * WooCommerceShippingZoneMethod
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.20.0-SNAPSHOT")
public class WooCommerceShippingZoneMethod {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private Integer id;

  public static final String SERIALIZED_NAME_INSTANCE_ID = "instance_id";
  @SerializedName(SERIALIZED_NAME_INSTANCE_ID)
  @javax.annotation.Nullable
  private Integer instanceId;

  public static final String SERIALIZED_NAME_TITLE = "title";
  @SerializedName(SERIALIZED_NAME_TITLE)
  @javax.annotation.Nullable
  private String title;

  public static final String SERIALIZED_NAME_ORDER = "order";
  @SerializedName(SERIALIZED_NAME_ORDER)
  @javax.annotation.Nullable
  private Integer order;

  public static final String SERIALIZED_NAME_ENABLED = "enabled";
  @SerializedName(SERIALIZED_NAME_ENABLED)
  @javax.annotation.Nullable
  private Boolean enabled;

  public static final String SERIALIZED_NAME_METHOD_ID = "method_id";
  @SerializedName(SERIALIZED_NAME_METHOD_ID)
  @javax.annotation.Nullable
  private String methodId;

  public static final String SERIALIZED_NAME_METHOD_TITLE = "method_title";
  @SerializedName(SERIALIZED_NAME_METHOD_TITLE)
  @javax.annotation.Nullable
  private String methodTitle;

  public static final String SERIALIZED_NAME_METHOD_DESCRIPTION = "method_description";
  @SerializedName(SERIALIZED_NAME_METHOD_DESCRIPTION)
  @javax.annotation.Nullable
  private String methodDescription;

  public static final String SERIALIZED_NAME_SETTINGS = "settings";
  @SerializedName(SERIALIZED_NAME_SETTINGS)
  @javax.annotation.Nullable
  private WooCommerceWcV3ShippingZonesZoneIdMethodsPostRequestSettings settings;

  public WooCommerceShippingZoneMethod() {
  }

  public WooCommerceShippingZoneMethod id(@javax.annotation.Nullable Integer id) {
    this.id = id;
    return this;
  }

  /**
   * Shipping method instance ID.
   * @return id
   */
  @javax.annotation.Nullable
  public Integer getId() {
    return id;
  }

  public void setId(@javax.annotation.Nullable Integer id) {
    this.id = id;
  }


  public WooCommerceShippingZoneMethod instanceId(@javax.annotation.Nullable Integer instanceId) {
    this.instanceId = instanceId;
    return this;
  }

  /**
   * Shipping method instance ID.
   * @return instanceId
   */
  @javax.annotation.Nullable
  public Integer getInstanceId() {
    return instanceId;
  }

  public void setInstanceId(@javax.annotation.Nullable Integer instanceId) {
    this.instanceId = instanceId;
  }


  public WooCommerceShippingZoneMethod title(@javax.annotation.Nullable String title) {
    this.title = title;
    return this;
  }

  /**
   * Shipping method customer facing title.
   * @return title
   */
  @javax.annotation.Nullable
  public String getTitle() {
    return title;
  }

  public void setTitle(@javax.annotation.Nullable String title) {
    this.title = title;
  }


  public WooCommerceShippingZoneMethod order(@javax.annotation.Nullable Integer order) {
    this.order = order;
    return this;
  }

  /**
   * Shipping method sort order.
   * @return order
   */
  @javax.annotation.Nullable
  public Integer getOrder() {
    return order;
  }

  public void setOrder(@javax.annotation.Nullable Integer order) {
    this.order = order;
  }


  public WooCommerceShippingZoneMethod enabled(@javax.annotation.Nullable Boolean enabled) {
    this.enabled = enabled;
    return this;
  }

  /**
   * Shipping method enabled status.
   * @return enabled
   */
  @javax.annotation.Nullable
  public Boolean getEnabled() {
    return enabled;
  }

  public void setEnabled(@javax.annotation.Nullable Boolean enabled) {
    this.enabled = enabled;
  }


  public WooCommerceShippingZoneMethod methodId(@javax.annotation.Nullable String methodId) {
    this.methodId = methodId;
    return this;
  }

  /**
   * Shipping method ID.
   * @return methodId
   */
  @javax.annotation.Nullable
  public String getMethodId() {
    return methodId;
  }

  public void setMethodId(@javax.annotation.Nullable String methodId) {
    this.methodId = methodId;
  }


  public WooCommerceShippingZoneMethod methodTitle(@javax.annotation.Nullable String methodTitle) {
    this.methodTitle = methodTitle;
    return this;
  }

  /**
   * Shipping method title.
   * @return methodTitle
   */
  @javax.annotation.Nullable
  public String getMethodTitle() {
    return methodTitle;
  }

  public void setMethodTitle(@javax.annotation.Nullable String methodTitle) {
    this.methodTitle = methodTitle;
  }


  public WooCommerceShippingZoneMethod methodDescription(@javax.annotation.Nullable String methodDescription) {
    this.methodDescription = methodDescription;
    return this;
  }

  /**
   * Shipping method description.
   * @return methodDescription
   */
  @javax.annotation.Nullable
  public String getMethodDescription() {
    return methodDescription;
  }

  public void setMethodDescription(@javax.annotation.Nullable String methodDescription) {
    this.methodDescription = methodDescription;
  }


  public WooCommerceShippingZoneMethod settings(@javax.annotation.Nullable WooCommerceWcV3ShippingZonesZoneIdMethodsPostRequestSettings settings) {
    this.settings = settings;
    return this;
  }

  /**
   * Get settings
   * @return settings
   */
  @javax.annotation.Nullable
  public WooCommerceWcV3ShippingZonesZoneIdMethodsPostRequestSettings getSettings() {
    return settings;
  }

  public void setSettings(@javax.annotation.Nullable WooCommerceWcV3ShippingZonesZoneIdMethodsPostRequestSettings settings) {
    this.settings = settings;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the WooCommerceShippingZoneMethod instance itself
   */
  public WooCommerceShippingZoneMethod putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WooCommerceShippingZoneMethod shippingZoneMethod = (WooCommerceShippingZoneMethod) o;
    return Objects.equals(this.id, shippingZoneMethod.id) &&
        Objects.equals(this.instanceId, shippingZoneMethod.instanceId) &&
        Objects.equals(this.title, shippingZoneMethod.title) &&
        Objects.equals(this.order, shippingZoneMethod.order) &&
        Objects.equals(this.enabled, shippingZoneMethod.enabled) &&
        Objects.equals(this.methodId, shippingZoneMethod.methodId) &&
        Objects.equals(this.methodTitle, shippingZoneMethod.methodTitle) &&
        Objects.equals(this.methodDescription, shippingZoneMethod.methodDescription) &&
        Objects.equals(this.settings, shippingZoneMethod.settings)&&
        Objects.equals(this.additionalProperties, shippingZoneMethod.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, instanceId, title, order, enabled, methodId, methodTitle, methodDescription, settings, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WooCommerceShippingZoneMethod {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    instanceId: ").append(toIndentedString(instanceId)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    order: ").append(toIndentedString(order)).append("\n");
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("    methodId: ").append(toIndentedString(methodId)).append("\n");
    sb.append("    methodTitle: ").append(toIndentedString(methodTitle)).append("\n");
    sb.append("    methodDescription: ").append(toIndentedString(methodDescription)).append("\n");
    sb.append("    settings: ").append(toIndentedString(settings)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("id", "instance_id", "title", "order", "enabled", "method_id", "method_title", "method_description", "settings"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to WooCommerceShippingZoneMethod
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!WooCommerceShippingZoneMethod.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in WooCommerceShippingZoneMethod is not found in the empty JSON string", WooCommerceShippingZoneMethod.openapiRequiredFields.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("title") != null && !jsonObj.get("title").isJsonNull()) && !jsonObj.get("title").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `title` to be a primitive type in the JSON string but got `%s`", jsonObj.get("title").toString()));
      }
      if ((jsonObj.get("method_id") != null && !jsonObj.get("method_id").isJsonNull()) && !jsonObj.get("method_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `method_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("method_id").toString()));
      }
      if ((jsonObj.get("method_title") != null && !jsonObj.get("method_title").isJsonNull()) && !jsonObj.get("method_title").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `method_title` to be a primitive type in the JSON string but got `%s`", jsonObj.get("method_title").toString()));
      }
      if ((jsonObj.get("method_description") != null && !jsonObj.get("method_description").isJsonNull()) && !jsonObj.get("method_description").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `method_description` to be a primitive type in the JSON string but got `%s`", jsonObj.get("method_description").toString()));
      }
      // validate the optional field `settings`
      if (jsonObj.get("settings") != null && !jsonObj.get("settings").isJsonNull()) {
        WooCommerceWcV3ShippingZonesZoneIdMethodsPostRequestSettings.validateJsonElement(jsonObj.get("settings"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!WooCommerceShippingZoneMethod.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'WooCommerceShippingZoneMethod' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<WooCommerceShippingZoneMethod> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(WooCommerceShippingZoneMethod.class));

       return (TypeAdapter<T>) new TypeAdapter<WooCommerceShippingZoneMethod>() {
           @Override
           public void write(JsonWriter out, WooCommerceShippingZoneMethod value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public WooCommerceShippingZoneMethod read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             WooCommerceShippingZoneMethod instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of WooCommerceShippingZoneMethod given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of WooCommerceShippingZoneMethod
   * @throws IOException if the JSON string is invalid with respect to WooCommerceShippingZoneMethod
   */
  public static WooCommerceShippingZoneMethod fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, WooCommerceShippingZoneMethod.class);
  }

  /**
   * Convert an instance of WooCommerceShippingZoneMethod to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

