/*
 * Dev Store API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.9.1
 * Contact: admin@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.woocommerce.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.woocommerce.JSON;

/**
 * Logging.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.20.0-SNAPSHOT")
public class WooCommerceSystemStatusLogging {
  public static final String SERIALIZED_NAME_LOGGING_ENABLED = "logging_enabled";
  @SerializedName(SERIALIZED_NAME_LOGGING_ENABLED)
  @javax.annotation.Nullable
  private Boolean loggingEnabled;

  public static final String SERIALIZED_NAME_DEFAULT_HANDLER = "default_handler";
  @SerializedName(SERIALIZED_NAME_DEFAULT_HANDLER)
  @javax.annotation.Nullable
  private String defaultHandler;

  public static final String SERIALIZED_NAME_RETENTION_PERIOD_DAYS = "retention_period_days";
  @SerializedName(SERIALIZED_NAME_RETENTION_PERIOD_DAYS)
  @javax.annotation.Nullable
  private Integer retentionPeriodDays;

  public static final String SERIALIZED_NAME_LEVEL_THRESHOLD = "level_threshold";
  @SerializedName(SERIALIZED_NAME_LEVEL_THRESHOLD)
  @javax.annotation.Nullable
  private String levelThreshold;

  public static final String SERIALIZED_NAME_LOG_DIRECTORY_SIZE = "log_directory_size";
  @SerializedName(SERIALIZED_NAME_LOG_DIRECTORY_SIZE)
  @javax.annotation.Nullable
  private String logDirectorySize;

  public WooCommerceSystemStatusLogging() {
  }

  public WooCommerceSystemStatusLogging loggingEnabled(@javax.annotation.Nullable Boolean loggingEnabled) {
    this.loggingEnabled = loggingEnabled;
    return this;
  }

  /**
   * Is logging enabled?
   * @return loggingEnabled
   */
  @javax.annotation.Nullable
  public Boolean getLoggingEnabled() {
    return loggingEnabled;
  }

  public void setLoggingEnabled(@javax.annotation.Nullable Boolean loggingEnabled) {
    this.loggingEnabled = loggingEnabled;
  }


  public WooCommerceSystemStatusLogging defaultHandler(@javax.annotation.Nullable String defaultHandler) {
    this.defaultHandler = defaultHandler;
    return this;
  }

  /**
   * The logging handler class.
   * @return defaultHandler
   */
  @javax.annotation.Nullable
  public String getDefaultHandler() {
    return defaultHandler;
  }

  public void setDefaultHandler(@javax.annotation.Nullable String defaultHandler) {
    this.defaultHandler = defaultHandler;
  }


  public WooCommerceSystemStatusLogging retentionPeriodDays(@javax.annotation.Nullable Integer retentionPeriodDays) {
    this.retentionPeriodDays = retentionPeriodDays;
    return this;
  }

  /**
   * The number of days log entries are retained.
   * @return retentionPeriodDays
   */
  @javax.annotation.Nullable
  public Integer getRetentionPeriodDays() {
    return retentionPeriodDays;
  }

  public void setRetentionPeriodDays(@javax.annotation.Nullable Integer retentionPeriodDays) {
    this.retentionPeriodDays = retentionPeriodDays;
  }


  public WooCommerceSystemStatusLogging levelThreshold(@javax.annotation.Nullable String levelThreshold) {
    this.levelThreshold = levelThreshold;
    return this;
  }

  /**
   * Minimum severity level.
   * @return levelThreshold
   */
  @javax.annotation.Nullable
  public String getLevelThreshold() {
    return levelThreshold;
  }

  public void setLevelThreshold(@javax.annotation.Nullable String levelThreshold) {
    this.levelThreshold = levelThreshold;
  }


  public WooCommerceSystemStatusLogging logDirectorySize(@javax.annotation.Nullable String logDirectorySize) {
    this.logDirectorySize = logDirectorySize;
    return this;
  }

  /**
   * The size of the log directory.
   * @return logDirectorySize
   */
  @javax.annotation.Nullable
  public String getLogDirectorySize() {
    return logDirectorySize;
  }

  public void setLogDirectorySize(@javax.annotation.Nullable String logDirectorySize) {
    this.logDirectorySize = logDirectorySize;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the WooCommerceSystemStatusLogging instance itself
   */
  public WooCommerceSystemStatusLogging putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WooCommerceSystemStatusLogging systemStatusLogging = (WooCommerceSystemStatusLogging) o;
    return Objects.equals(this.loggingEnabled, systemStatusLogging.loggingEnabled) &&
        Objects.equals(this.defaultHandler, systemStatusLogging.defaultHandler) &&
        Objects.equals(this.retentionPeriodDays, systemStatusLogging.retentionPeriodDays) &&
        Objects.equals(this.levelThreshold, systemStatusLogging.levelThreshold) &&
        Objects.equals(this.logDirectorySize, systemStatusLogging.logDirectorySize)&&
        Objects.equals(this.additionalProperties, systemStatusLogging.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(loggingEnabled, defaultHandler, retentionPeriodDays, levelThreshold, logDirectorySize, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WooCommerceSystemStatusLogging {\n");
    sb.append("    loggingEnabled: ").append(toIndentedString(loggingEnabled)).append("\n");
    sb.append("    defaultHandler: ").append(toIndentedString(defaultHandler)).append("\n");
    sb.append("    retentionPeriodDays: ").append(toIndentedString(retentionPeriodDays)).append("\n");
    sb.append("    levelThreshold: ").append(toIndentedString(levelThreshold)).append("\n");
    sb.append("    logDirectorySize: ").append(toIndentedString(logDirectorySize)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("logging_enabled", "default_handler", "retention_period_days", "level_threshold", "log_directory_size"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to WooCommerceSystemStatusLogging
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!WooCommerceSystemStatusLogging.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in WooCommerceSystemStatusLogging is not found in the empty JSON string", WooCommerceSystemStatusLogging.openapiRequiredFields.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("default_handler") != null && !jsonObj.get("default_handler").isJsonNull()) && !jsonObj.get("default_handler").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `default_handler` to be a primitive type in the JSON string but got `%s`", jsonObj.get("default_handler").toString()));
      }
      if ((jsonObj.get("level_threshold") != null && !jsonObj.get("level_threshold").isJsonNull()) && !jsonObj.get("level_threshold").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `level_threshold` to be a primitive type in the JSON string but got `%s`", jsonObj.get("level_threshold").toString()));
      }
      if ((jsonObj.get("log_directory_size") != null && !jsonObj.get("log_directory_size").isJsonNull()) && !jsonObj.get("log_directory_size").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `log_directory_size` to be a primitive type in the JSON string but got `%s`", jsonObj.get("log_directory_size").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!WooCommerceSystemStatusLogging.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'WooCommerceSystemStatusLogging' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<WooCommerceSystemStatusLogging> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(WooCommerceSystemStatusLogging.class));

       return (TypeAdapter<T>) new TypeAdapter<WooCommerceSystemStatusLogging>() {
           @Override
           public void write(JsonWriter out, WooCommerceSystemStatusLogging value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public WooCommerceSystemStatusLogging read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             WooCommerceSystemStatusLogging instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of WooCommerceSystemStatusLogging given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of WooCommerceSystemStatusLogging
   * @throws IOException if the JSON string is invalid with respect to WooCommerceSystemStatusLogging
   */
  public static WooCommerceSystemStatusLogging fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, WooCommerceSystemStatusLogging.class);
  }

  /**
   * Convert an instance of WooCommerceSystemStatusLogging to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

