/*
 * Dev Store API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.9.1
 * Contact: admin@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.woocommerce.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.woocommerce.model.WooCommerceShopOrderLineItemsInnerMetaDataInner;
import com.woocommerce.model.WooCommerceWcV3OrdersOrderIdRefundsPostRequestFeeLinesInnerTaxesInner;
import com.woocommerce.model.WooCommerceWcV3OrdersPostRequestLineItemsInnerImage;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.woocommerce.JSON;

/**
 * WooCommerceShopOrderLineItemsInner
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.20.0-SNAPSHOT")
public class WooCommerceShopOrderLineItemsInner {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private Integer id;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nullable
  private String name;

  public static final String SERIALIZED_NAME_PARENT_NAME = "parent_name";
  @SerializedName(SERIALIZED_NAME_PARENT_NAME)
  @javax.annotation.Nullable
  private String parentName;

  public static final String SERIALIZED_NAME_PRODUCT_ID = "product_id";
  @SerializedName(SERIALIZED_NAME_PRODUCT_ID)
  @javax.annotation.Nullable
  private String productId;

  public static final String SERIALIZED_NAME_VARIATION_ID = "variation_id";
  @SerializedName(SERIALIZED_NAME_VARIATION_ID)
  @javax.annotation.Nullable
  private Integer variationId;

  public static final String SERIALIZED_NAME_QUANTITY = "quantity";
  @SerializedName(SERIALIZED_NAME_QUANTITY)
  @javax.annotation.Nullable
  private Integer quantity;

  public static final String SERIALIZED_NAME_TAX_CLASS = "tax_class";
  @SerializedName(SERIALIZED_NAME_TAX_CLASS)
  @javax.annotation.Nullable
  private String taxClass;

  public static final String SERIALIZED_NAME_SUBTOTAL = "subtotal";
  @SerializedName(SERIALIZED_NAME_SUBTOTAL)
  @javax.annotation.Nullable
  private String subtotal;

  public static final String SERIALIZED_NAME_SUBTOTAL_TAX = "subtotal_tax";
  @SerializedName(SERIALIZED_NAME_SUBTOTAL_TAX)
  @javax.annotation.Nullable
  private String subtotalTax;

  public static final String SERIALIZED_NAME_TOTAL = "total";
  @SerializedName(SERIALIZED_NAME_TOTAL)
  @javax.annotation.Nullable
  private String total;

  public static final String SERIALIZED_NAME_TOTAL_TAX = "total_tax";
  @SerializedName(SERIALIZED_NAME_TOTAL_TAX)
  @javax.annotation.Nullable
  private String totalTax;

  public static final String SERIALIZED_NAME_TAXES = "taxes";
  @SerializedName(SERIALIZED_NAME_TAXES)
  @javax.annotation.Nullable
  private List<WooCommerceWcV3OrdersOrderIdRefundsPostRequestFeeLinesInnerTaxesInner> taxes = new ArrayList<>();

  public static final String SERIALIZED_NAME_META_DATA = "meta_data";
  @SerializedName(SERIALIZED_NAME_META_DATA)
  @javax.annotation.Nullable
  private List<WooCommerceShopOrderLineItemsInnerMetaDataInner> metaData = new ArrayList<>();

  public static final String SERIALIZED_NAME_SKU = "sku";
  @SerializedName(SERIALIZED_NAME_SKU)
  @javax.annotation.Nullable
  private String sku;

  public static final String SERIALIZED_NAME_GLOBAL_UNIQUE_ID = "global_unique_id";
  @SerializedName(SERIALIZED_NAME_GLOBAL_UNIQUE_ID)
  @javax.annotation.Nullable
  private String globalUniqueId;

  public static final String SERIALIZED_NAME_PRICE = "price";
  @SerializedName(SERIALIZED_NAME_PRICE)
  @javax.annotation.Nullable
  private BigDecimal price;

  public static final String SERIALIZED_NAME_IMAGE = "image";
  @SerializedName(SERIALIZED_NAME_IMAGE)
  @javax.annotation.Nullable
  private WooCommerceWcV3OrdersPostRequestLineItemsInnerImage image;

  public WooCommerceShopOrderLineItemsInner() {
  }

  public WooCommerceShopOrderLineItemsInner id(@javax.annotation.Nullable Integer id) {
    this.id = id;
    return this;
  }

  /**
   * Item ID.
   * @return id
   */
  @javax.annotation.Nullable
  public Integer getId() {
    return id;
  }

  public void setId(@javax.annotation.Nullable Integer id) {
    this.id = id;
  }


  public WooCommerceShopOrderLineItemsInner name(@javax.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * Product name.
   * @return name
   */
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }


  public WooCommerceShopOrderLineItemsInner parentName(@javax.annotation.Nullable String parentName) {
    this.parentName = parentName;
    return this;
  }

  /**
   * Parent product name if the product is a variation.
   * @return parentName
   */
  @javax.annotation.Nullable
  public String getParentName() {
    return parentName;
  }

  public void setParentName(@javax.annotation.Nullable String parentName) {
    this.parentName = parentName;
  }


  public WooCommerceShopOrderLineItemsInner productId(@javax.annotation.Nullable String productId) {
    this.productId = productId;
    return this;
  }

  /**
   * Product ID.
   * @return productId
   */
  @javax.annotation.Nullable
  public String getProductId() {
    return productId;
  }

  public void setProductId(@javax.annotation.Nullable String productId) {
    this.productId = productId;
  }


  public WooCommerceShopOrderLineItemsInner variationId(@javax.annotation.Nullable Integer variationId) {
    this.variationId = variationId;
    return this;
  }

  /**
   * Variation ID, if applicable.
   * @return variationId
   */
  @javax.annotation.Nullable
  public Integer getVariationId() {
    return variationId;
  }

  public void setVariationId(@javax.annotation.Nullable Integer variationId) {
    this.variationId = variationId;
  }


  public WooCommerceShopOrderLineItemsInner quantity(@javax.annotation.Nullable Integer quantity) {
    this.quantity = quantity;
    return this;
  }

  /**
   * Quantity ordered.
   * @return quantity
   */
  @javax.annotation.Nullable
  public Integer getQuantity() {
    return quantity;
  }

  public void setQuantity(@javax.annotation.Nullable Integer quantity) {
    this.quantity = quantity;
  }


  public WooCommerceShopOrderLineItemsInner taxClass(@javax.annotation.Nullable String taxClass) {
    this.taxClass = taxClass;
    return this;
  }

  /**
   * Tax class of product.
   * @return taxClass
   */
  @javax.annotation.Nullable
  public String getTaxClass() {
    return taxClass;
  }

  public void setTaxClass(@javax.annotation.Nullable String taxClass) {
    this.taxClass = taxClass;
  }


  public WooCommerceShopOrderLineItemsInner subtotal(@javax.annotation.Nullable String subtotal) {
    this.subtotal = subtotal;
    return this;
  }

  /**
   * Line subtotal (before discounts).
   * @return subtotal
   */
  @javax.annotation.Nullable
  public String getSubtotal() {
    return subtotal;
  }

  public void setSubtotal(@javax.annotation.Nullable String subtotal) {
    this.subtotal = subtotal;
  }


  public WooCommerceShopOrderLineItemsInner subtotalTax(@javax.annotation.Nullable String subtotalTax) {
    this.subtotalTax = subtotalTax;
    return this;
  }

  /**
   * Line subtotal tax (before discounts).
   * @return subtotalTax
   */
  @javax.annotation.Nullable
  public String getSubtotalTax() {
    return subtotalTax;
  }

  public void setSubtotalTax(@javax.annotation.Nullable String subtotalTax) {
    this.subtotalTax = subtotalTax;
  }


  public WooCommerceShopOrderLineItemsInner total(@javax.annotation.Nullable String total) {
    this.total = total;
    return this;
  }

  /**
   * Line total (after discounts).
   * @return total
   */
  @javax.annotation.Nullable
  public String getTotal() {
    return total;
  }

  public void setTotal(@javax.annotation.Nullable String total) {
    this.total = total;
  }


  public WooCommerceShopOrderLineItemsInner totalTax(@javax.annotation.Nullable String totalTax) {
    this.totalTax = totalTax;
    return this;
  }

  /**
   * Line total tax (after discounts).
   * @return totalTax
   */
  @javax.annotation.Nullable
  public String getTotalTax() {
    return totalTax;
  }

  public void setTotalTax(@javax.annotation.Nullable String totalTax) {
    this.totalTax = totalTax;
  }


  public WooCommerceShopOrderLineItemsInner taxes(@javax.annotation.Nullable List<WooCommerceWcV3OrdersOrderIdRefundsPostRequestFeeLinesInnerTaxesInner> taxes) {
    this.taxes = taxes;
    return this;
  }

  public WooCommerceShopOrderLineItemsInner addTaxesItem(WooCommerceWcV3OrdersOrderIdRefundsPostRequestFeeLinesInnerTaxesInner taxesItem) {
    if (this.taxes == null) {
      this.taxes = new ArrayList<>();
    }
    this.taxes.add(taxesItem);
    return this;
  }

  /**
   * Line taxes.
   * @return taxes
   */
  @javax.annotation.Nullable
  public List<WooCommerceWcV3OrdersOrderIdRefundsPostRequestFeeLinesInnerTaxesInner> getTaxes() {
    return taxes;
  }

  public void setTaxes(@javax.annotation.Nullable List<WooCommerceWcV3OrdersOrderIdRefundsPostRequestFeeLinesInnerTaxesInner> taxes) {
    this.taxes = taxes;
  }


  public WooCommerceShopOrderLineItemsInner metaData(@javax.annotation.Nullable List<WooCommerceShopOrderLineItemsInnerMetaDataInner> metaData) {
    this.metaData = metaData;
    return this;
  }

  public WooCommerceShopOrderLineItemsInner addMetaDataItem(WooCommerceShopOrderLineItemsInnerMetaDataInner metaDataItem) {
    if (this.metaData == null) {
      this.metaData = new ArrayList<>();
    }
    this.metaData.add(metaDataItem);
    return this;
  }

  /**
   * Meta data.
   * @return metaData
   */
  @javax.annotation.Nullable
  public List<WooCommerceShopOrderLineItemsInnerMetaDataInner> getMetaData() {
    return metaData;
  }

  public void setMetaData(@javax.annotation.Nullable List<WooCommerceShopOrderLineItemsInnerMetaDataInner> metaData) {
    this.metaData = metaData;
  }


  public WooCommerceShopOrderLineItemsInner sku(@javax.annotation.Nullable String sku) {
    this.sku = sku;
    return this;
  }

  /**
   * Product SKU.
   * @return sku
   */
  @javax.annotation.Nullable
  public String getSku() {
    return sku;
  }

  public void setSku(@javax.annotation.Nullable String sku) {
    this.sku = sku;
  }


  public WooCommerceShopOrderLineItemsInner globalUniqueId(@javax.annotation.Nullable String globalUniqueId) {
    this.globalUniqueId = globalUniqueId;
    return this;
  }

  /**
   * GTIN, UPC, EAN or ISBN.
   * @return globalUniqueId
   */
  @javax.annotation.Nullable
  public String getGlobalUniqueId() {
    return globalUniqueId;
  }

  public void setGlobalUniqueId(@javax.annotation.Nullable String globalUniqueId) {
    this.globalUniqueId = globalUniqueId;
  }


  public WooCommerceShopOrderLineItemsInner price(@javax.annotation.Nullable BigDecimal price) {
    this.price = price;
    return this;
  }

  /**
   * Product price.
   * @return price
   */
  @javax.annotation.Nullable
  public BigDecimal getPrice() {
    return price;
  }

  public void setPrice(@javax.annotation.Nullable BigDecimal price) {
    this.price = price;
  }


  public WooCommerceShopOrderLineItemsInner image(@javax.annotation.Nullable WooCommerceWcV3OrdersPostRequestLineItemsInnerImage image) {
    this.image = image;
    return this;
  }

  /**
   * Get image
   * @return image
   */
  @javax.annotation.Nullable
  public WooCommerceWcV3OrdersPostRequestLineItemsInnerImage getImage() {
    return image;
  }

  public void setImage(@javax.annotation.Nullable WooCommerceWcV3OrdersPostRequestLineItemsInnerImage image) {
    this.image = image;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the WooCommerceShopOrderLineItemsInner instance itself
   */
  public WooCommerceShopOrderLineItemsInner putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WooCommerceShopOrderLineItemsInner shopOrderLineItemsInner = (WooCommerceShopOrderLineItemsInner) o;
    return Objects.equals(this.id, shopOrderLineItemsInner.id) &&
        Objects.equals(this.name, shopOrderLineItemsInner.name) &&
        Objects.equals(this.parentName, shopOrderLineItemsInner.parentName) &&
        Objects.equals(this.productId, shopOrderLineItemsInner.productId) &&
        Objects.equals(this.variationId, shopOrderLineItemsInner.variationId) &&
        Objects.equals(this.quantity, shopOrderLineItemsInner.quantity) &&
        Objects.equals(this.taxClass, shopOrderLineItemsInner.taxClass) &&
        Objects.equals(this.subtotal, shopOrderLineItemsInner.subtotal) &&
        Objects.equals(this.subtotalTax, shopOrderLineItemsInner.subtotalTax) &&
        Objects.equals(this.total, shopOrderLineItemsInner.total) &&
        Objects.equals(this.totalTax, shopOrderLineItemsInner.totalTax) &&
        Objects.equals(this.taxes, shopOrderLineItemsInner.taxes) &&
        Objects.equals(this.metaData, shopOrderLineItemsInner.metaData) &&
        Objects.equals(this.sku, shopOrderLineItemsInner.sku) &&
        Objects.equals(this.globalUniqueId, shopOrderLineItemsInner.globalUniqueId) &&
        Objects.equals(this.price, shopOrderLineItemsInner.price) &&
        Objects.equals(this.image, shopOrderLineItemsInner.image)&&
        Objects.equals(this.additionalProperties, shopOrderLineItemsInner.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, parentName, productId, variationId, quantity, taxClass, subtotal, subtotalTax, total, totalTax, taxes, metaData, sku, globalUniqueId, price, image, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WooCommerceShopOrderLineItemsInner {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    parentName: ").append(toIndentedString(parentName)).append("\n");
    sb.append("    productId: ").append(toIndentedString(productId)).append("\n");
    sb.append("    variationId: ").append(toIndentedString(variationId)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    taxClass: ").append(toIndentedString(taxClass)).append("\n");
    sb.append("    subtotal: ").append(toIndentedString(subtotal)).append("\n");
    sb.append("    subtotalTax: ").append(toIndentedString(subtotalTax)).append("\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("    totalTax: ").append(toIndentedString(totalTax)).append("\n");
    sb.append("    taxes: ").append(toIndentedString(taxes)).append("\n");
    sb.append("    metaData: ").append(toIndentedString(metaData)).append("\n");
    sb.append("    sku: ").append(toIndentedString(sku)).append("\n");
    sb.append("    globalUniqueId: ").append(toIndentedString(globalUniqueId)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    image: ").append(toIndentedString(image)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("id", "name", "parent_name", "product_id", "variation_id", "quantity", "tax_class", "subtotal", "subtotal_tax", "total", "total_tax", "taxes", "meta_data", "sku", "global_unique_id", "price", "image"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to WooCommerceShopOrderLineItemsInner
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!WooCommerceShopOrderLineItemsInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in WooCommerceShopOrderLineItemsInner is not found in the empty JSON string", WooCommerceShopOrderLineItemsInner.openapiRequiredFields.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("parent_name") != null && !jsonObj.get("parent_name").isJsonNull()) && !jsonObj.get("parent_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `parent_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("parent_name").toString()));
      }
      if ((jsonObj.get("product_id") != null && !jsonObj.get("product_id").isJsonNull()) && !jsonObj.get("product_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `product_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("product_id").toString()));
      }
      if ((jsonObj.get("tax_class") != null && !jsonObj.get("tax_class").isJsonNull()) && !jsonObj.get("tax_class").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `tax_class` to be a primitive type in the JSON string but got `%s`", jsonObj.get("tax_class").toString()));
      }
      if ((jsonObj.get("subtotal") != null && !jsonObj.get("subtotal").isJsonNull()) && !jsonObj.get("subtotal").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `subtotal` to be a primitive type in the JSON string but got `%s`", jsonObj.get("subtotal").toString()));
      }
      if ((jsonObj.get("subtotal_tax") != null && !jsonObj.get("subtotal_tax").isJsonNull()) && !jsonObj.get("subtotal_tax").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `subtotal_tax` to be a primitive type in the JSON string but got `%s`", jsonObj.get("subtotal_tax").toString()));
      }
      if ((jsonObj.get("total") != null && !jsonObj.get("total").isJsonNull()) && !jsonObj.get("total").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `total` to be a primitive type in the JSON string but got `%s`", jsonObj.get("total").toString()));
      }
      if ((jsonObj.get("total_tax") != null && !jsonObj.get("total_tax").isJsonNull()) && !jsonObj.get("total_tax").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `total_tax` to be a primitive type in the JSON string but got `%s`", jsonObj.get("total_tax").toString()));
      }
      if (jsonObj.get("taxes") != null && !jsonObj.get("taxes").isJsonNull()) {
        JsonArray jsonArraytaxes = jsonObj.getAsJsonArray("taxes");
        if (jsonArraytaxes != null) {
          // ensure the json data is an array
          if (!jsonObj.get("taxes").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `taxes` to be an array in the JSON string but got `%s`", jsonObj.get("taxes").toString()));
          }

          // validate the optional field `taxes` (array)
          for (int i = 0; i < jsonArraytaxes.size(); i++) {
            WooCommerceWcV3OrdersOrderIdRefundsPostRequestFeeLinesInnerTaxesInner.validateJsonElement(jsonArraytaxes.get(i));
          };
        }
      }
      if (jsonObj.get("meta_data") != null && !jsonObj.get("meta_data").isJsonNull()) {
        JsonArray jsonArraymetaData = jsonObj.getAsJsonArray("meta_data");
        if (jsonArraymetaData != null) {
          // ensure the json data is an array
          if (!jsonObj.get("meta_data").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `meta_data` to be an array in the JSON string but got `%s`", jsonObj.get("meta_data").toString()));
          }

          // validate the optional field `meta_data` (array)
          for (int i = 0; i < jsonArraymetaData.size(); i++) {
            WooCommerceShopOrderLineItemsInnerMetaDataInner.validateJsonElement(jsonArraymetaData.get(i));
          };
        }
      }
      if ((jsonObj.get("sku") != null && !jsonObj.get("sku").isJsonNull()) && !jsonObj.get("sku").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `sku` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sku").toString()));
      }
      if ((jsonObj.get("global_unique_id") != null && !jsonObj.get("global_unique_id").isJsonNull()) && !jsonObj.get("global_unique_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `global_unique_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("global_unique_id").toString()));
      }
      // validate the optional field `image`
      if (jsonObj.get("image") != null && !jsonObj.get("image").isJsonNull()) {
        WooCommerceWcV3OrdersPostRequestLineItemsInnerImage.validateJsonElement(jsonObj.get("image"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!WooCommerceShopOrderLineItemsInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'WooCommerceShopOrderLineItemsInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<WooCommerceShopOrderLineItemsInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(WooCommerceShopOrderLineItemsInner.class));

       return (TypeAdapter<T>) new TypeAdapter<WooCommerceShopOrderLineItemsInner>() {
           @Override
           public void write(JsonWriter out, WooCommerceShopOrderLineItemsInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public WooCommerceShopOrderLineItemsInner read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             WooCommerceShopOrderLineItemsInner instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of WooCommerceShopOrderLineItemsInner given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of WooCommerceShopOrderLineItemsInner
   * @throws IOException if the JSON string is invalid with respect to WooCommerceShopOrderLineItemsInner
   */
  public static WooCommerceShopOrderLineItemsInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, WooCommerceShopOrderLineItemsInner.class);
  }

  /**
   * Convert an instance of WooCommerceShopOrderLineItemsInner to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

