/*
 * Dev Store API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.9.1
 * Contact: admin@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.woocommerce.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.woocommerce.model.WooCommerceWcV3CouponsPostRequestMetaDataInner;
import com.woocommerce.model.WooCommerceWcV3ProductsPostRequestDefaultAttributesInner;
import com.woocommerce.model.WooCommerceWcV3ProductsPostRequestDownloadsInner;
import com.woocommerce.model.WooCommerceWcV3ProductsProductIdVariationsGeneratePostRequestDefaultValuesDimensions;
import com.woocommerce.model.WooCommerceWcV3ProductsProductIdVariationsGeneratePostRequestDefaultValuesImage;
import com.woocommerce.model.WooCommerceWcV3ProductsProductIdVariationsGeneratePostRequestDefaultValuesManageStock;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.woocommerce.JSON;

/**
 * Default values for generated variations.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.20.0-SNAPSHOT")
public class WooCommerceWcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues {
  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  @javax.annotation.Nullable
  private String description;

  public static final String SERIALIZED_NAME_SKU = "sku";
  @SerializedName(SERIALIZED_NAME_SKU)
  @javax.annotation.Nullable
  private String sku;

  public static final String SERIALIZED_NAME_GLOBAL_UNIQUE_ID = "global_unique_id";
  @SerializedName(SERIALIZED_NAME_GLOBAL_UNIQUE_ID)
  @javax.annotation.Nullable
  private String globalUniqueId;

  public static final String SERIALIZED_NAME_REGULAR_PRICE = "regular_price";
  @SerializedName(SERIALIZED_NAME_REGULAR_PRICE)
  @javax.annotation.Nullable
  private String regularPrice;

  public static final String SERIALIZED_NAME_SALE_PRICE = "sale_price";
  @SerializedName(SERIALIZED_NAME_SALE_PRICE)
  @javax.annotation.Nullable
  private String salePrice;

  public static final String SERIALIZED_NAME_DATE_ON_SALE_FROM = "date_on_sale_from";
  @SerializedName(SERIALIZED_NAME_DATE_ON_SALE_FROM)
  @javax.annotation.Nullable
  private String dateOnSaleFrom;

  public static final String SERIALIZED_NAME_DATE_ON_SALE_FROM_GMT = "date_on_sale_from_gmt";
  @SerializedName(SERIALIZED_NAME_DATE_ON_SALE_FROM_GMT)
  @javax.annotation.Nullable
  private String dateOnSaleFromGmt;

  public static final String SERIALIZED_NAME_DATE_ON_SALE_TO = "date_on_sale_to";
  @SerializedName(SERIALIZED_NAME_DATE_ON_SALE_TO)
  @javax.annotation.Nullable
  private String dateOnSaleTo;

  public static final String SERIALIZED_NAME_DATE_ON_SALE_TO_GMT = "date_on_sale_to_gmt";
  @SerializedName(SERIALIZED_NAME_DATE_ON_SALE_TO_GMT)
  @javax.annotation.Nullable
  private String dateOnSaleToGmt;

  /**
   * Variation status.
   */
  @JsonAdapter(StatusEnum.Adapter.class)
  public enum StatusEnum {
    DRAFT("draft"),
    
    PENDING("pending"),
    
    PRIVATE("private"),
    
    PUBLISH("publish"),
    
    UNKNOWN_DEFAULT_OPEN_API("unknown_default_open_api");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return UNKNOWN_DEFAULT_OPEN_API;
    }

    public static class Adapter extends TypeAdapter<StatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StatusEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return StatusEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      StatusEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nullable
  private StatusEnum status;

  public static final String SERIALIZED_NAME_VIRTUAL = "virtual";
  @SerializedName(SERIALIZED_NAME_VIRTUAL)
  @javax.annotation.Nullable
  private Boolean virtual;

  public static final String SERIALIZED_NAME_DOWNLOADABLE = "downloadable";
  @SerializedName(SERIALIZED_NAME_DOWNLOADABLE)
  @javax.annotation.Nullable
  private Boolean downloadable;

  public static final String SERIALIZED_NAME_DOWNLOADS = "downloads";
  @SerializedName(SERIALIZED_NAME_DOWNLOADS)
  @javax.annotation.Nullable
  private List<WooCommerceWcV3ProductsPostRequestDownloadsInner> downloads = new ArrayList<>();

  public static final String SERIALIZED_NAME_DOWNLOAD_LIMIT = "download_limit";
  @SerializedName(SERIALIZED_NAME_DOWNLOAD_LIMIT)
  @javax.annotation.Nullable
  private Integer downloadLimit;

  public static final String SERIALIZED_NAME_DOWNLOAD_EXPIRY = "download_expiry";
  @SerializedName(SERIALIZED_NAME_DOWNLOAD_EXPIRY)
  @javax.annotation.Nullable
  private Integer downloadExpiry;

  /**
   * Tax status.
   */
  @JsonAdapter(TaxStatusEnum.Adapter.class)
  public enum TaxStatusEnum {
    TAXABLE("taxable"),
    
    SHIPPING("shipping"),
    
    NONE("none"),
    
    UNKNOWN_DEFAULT_OPEN_API("unknown_default_open_api");

    private String value;

    TaxStatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static TaxStatusEnum fromValue(String value) {
      for (TaxStatusEnum b : TaxStatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return UNKNOWN_DEFAULT_OPEN_API;
    }

    public static class Adapter extends TypeAdapter<TaxStatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TaxStatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public TaxStatusEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return TaxStatusEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      TaxStatusEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_TAX_STATUS = "tax_status";
  @SerializedName(SERIALIZED_NAME_TAX_STATUS)
  @javax.annotation.Nullable
  private TaxStatusEnum taxStatus;

  public static final String SERIALIZED_NAME_TAX_CLASS = "tax_class";
  @SerializedName(SERIALIZED_NAME_TAX_CLASS)
  @javax.annotation.Nullable
  private String taxClass;

  public static final String SERIALIZED_NAME_MANAGE_STOCK = "manage_stock";
  @SerializedName(SERIALIZED_NAME_MANAGE_STOCK)
  @javax.annotation.Nullable
  private WooCommerceWcV3ProductsProductIdVariationsGeneratePostRequestDefaultValuesManageStock manageStock;

  public static final String SERIALIZED_NAME_STOCK_QUANTITY = "stock_quantity";
  @SerializedName(SERIALIZED_NAME_STOCK_QUANTITY)
  @javax.annotation.Nullable
  private Integer stockQuantity;

  /**
   * Controls the stock status of the product.
   */
  @JsonAdapter(StockStatusEnum.Adapter.class)
  public enum StockStatusEnum {
    INSTOCK("instock"),
    
    OUTOFSTOCK("outofstock"),
    
    ONBACKORDER("onbackorder"),
    
    UNKNOWN_DEFAULT_OPEN_API("unknown_default_open_api");

    private String value;

    StockStatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StockStatusEnum fromValue(String value) {
      for (StockStatusEnum b : StockStatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return UNKNOWN_DEFAULT_OPEN_API;
    }

    public static class Adapter extends TypeAdapter<StockStatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StockStatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StockStatusEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return StockStatusEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      StockStatusEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_STOCK_STATUS = "stock_status";
  @SerializedName(SERIALIZED_NAME_STOCK_STATUS)
  @javax.annotation.Nullable
  private StockStatusEnum stockStatus;

  /**
   * If managing stock, this controls if backorders are allowed.
   */
  @JsonAdapter(BackordersEnum.Adapter.class)
  public enum BackordersEnum {
    NO("no"),
    
    NOTIFY("notify"),
    
    YES("yes"),
    
    UNKNOWN_DEFAULT_OPEN_API("unknown_default_open_api");

    private String value;

    BackordersEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static BackordersEnum fromValue(String value) {
      for (BackordersEnum b : BackordersEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return UNKNOWN_DEFAULT_OPEN_API;
    }

    public static class Adapter extends TypeAdapter<BackordersEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final BackordersEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public BackordersEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return BackordersEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      BackordersEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_BACKORDERS = "backorders";
  @SerializedName(SERIALIZED_NAME_BACKORDERS)
  @javax.annotation.Nullable
  private BackordersEnum backorders;

  public static final String SERIALIZED_NAME_LOW_STOCK_AMOUNT = "low_stock_amount";
  @SerializedName(SERIALIZED_NAME_LOW_STOCK_AMOUNT)
  @javax.annotation.Nullable
  private Integer lowStockAmount;

  public static final String SERIALIZED_NAME_WEIGHT = "weight";
  @SerializedName(SERIALIZED_NAME_WEIGHT)
  @javax.annotation.Nullable
  private String weight;

  public static final String SERIALIZED_NAME_DIMENSIONS = "dimensions";
  @SerializedName(SERIALIZED_NAME_DIMENSIONS)
  @javax.annotation.Nullable
  private WooCommerceWcV3ProductsProductIdVariationsGeneratePostRequestDefaultValuesDimensions dimensions;

  public static final String SERIALIZED_NAME_SHIPPING_CLASS = "shipping_class";
  @SerializedName(SERIALIZED_NAME_SHIPPING_CLASS)
  @javax.annotation.Nullable
  private String shippingClass;

  public static final String SERIALIZED_NAME_IMAGE = "image";
  @SerializedName(SERIALIZED_NAME_IMAGE)
  @javax.annotation.Nullable
  private WooCommerceWcV3ProductsProductIdVariationsGeneratePostRequestDefaultValuesImage image;

  public static final String SERIALIZED_NAME_ATTRIBUTES = "attributes";
  @SerializedName(SERIALIZED_NAME_ATTRIBUTES)
  @javax.annotation.Nullable
  private List<WooCommerceWcV3ProductsPostRequestDefaultAttributesInner> attributes = new ArrayList<>();

  public static final String SERIALIZED_NAME_MENU_ORDER = "menu_order";
  @SerializedName(SERIALIZED_NAME_MENU_ORDER)
  @javax.annotation.Nullable
  private Integer menuOrder;

  public static final String SERIALIZED_NAME_META_DATA = "meta_data";
  @SerializedName(SERIALIZED_NAME_META_DATA)
  @javax.annotation.Nullable
  private List<WooCommerceWcV3CouponsPostRequestMetaDataInner> metaData = new ArrayList<>();

  public WooCommerceWcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues() {
  }

  public WooCommerceWcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues description(@javax.annotation.Nullable String description) {
    this.description = description;
    return this;
  }

  /**
   * Variation description.
   * @return description
   */
  @javax.annotation.Nullable
  public String getDescription() {
    return description;
  }

  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }


  public WooCommerceWcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues sku(@javax.annotation.Nullable String sku) {
    this.sku = sku;
    return this;
  }

  /**
   * Stock Keeping Unit.
   * @return sku
   */
  @javax.annotation.Nullable
  public String getSku() {
    return sku;
  }

  public void setSku(@javax.annotation.Nullable String sku) {
    this.sku = sku;
  }


  public WooCommerceWcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues globalUniqueId(@javax.annotation.Nullable String globalUniqueId) {
    this.globalUniqueId = globalUniqueId;
    return this;
  }

  /**
   * GTIN, UPC, EAN or ISBN.
   * @return globalUniqueId
   */
  @javax.annotation.Nullable
  public String getGlobalUniqueId() {
    return globalUniqueId;
  }

  public void setGlobalUniqueId(@javax.annotation.Nullable String globalUniqueId) {
    this.globalUniqueId = globalUniqueId;
  }


  public WooCommerceWcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues regularPrice(@javax.annotation.Nullable String regularPrice) {
    this.regularPrice = regularPrice;
    return this;
  }

  /**
   * Variation regular price.
   * @return regularPrice
   */
  @javax.annotation.Nullable
  public String getRegularPrice() {
    return regularPrice;
  }

  public void setRegularPrice(@javax.annotation.Nullable String regularPrice) {
    this.regularPrice = regularPrice;
  }


  public WooCommerceWcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues salePrice(@javax.annotation.Nullable String salePrice) {
    this.salePrice = salePrice;
    return this;
  }

  /**
   * Variation sale price.
   * @return salePrice
   */
  @javax.annotation.Nullable
  public String getSalePrice() {
    return salePrice;
  }

  public void setSalePrice(@javax.annotation.Nullable String salePrice) {
    this.salePrice = salePrice;
  }


  public WooCommerceWcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues dateOnSaleFrom(@javax.annotation.Nullable String dateOnSaleFrom) {
    this.dateOnSaleFrom = dateOnSaleFrom;
    return this;
  }

  /**
   * Start date of sale price, in the site&#39;s timezone.
   * @return dateOnSaleFrom
   */
  @javax.annotation.Nullable
  public String getDateOnSaleFrom() {
    return dateOnSaleFrom;
  }

  public void setDateOnSaleFrom(@javax.annotation.Nullable String dateOnSaleFrom) {
    this.dateOnSaleFrom = dateOnSaleFrom;
  }


  public WooCommerceWcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues dateOnSaleFromGmt(@javax.annotation.Nullable String dateOnSaleFromGmt) {
    this.dateOnSaleFromGmt = dateOnSaleFromGmt;
    return this;
  }

  /**
   * Start date of sale price, as GMT.
   * @return dateOnSaleFromGmt
   */
  @javax.annotation.Nullable
  public String getDateOnSaleFromGmt() {
    return dateOnSaleFromGmt;
  }

  public void setDateOnSaleFromGmt(@javax.annotation.Nullable String dateOnSaleFromGmt) {
    this.dateOnSaleFromGmt = dateOnSaleFromGmt;
  }


  public WooCommerceWcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues dateOnSaleTo(@javax.annotation.Nullable String dateOnSaleTo) {
    this.dateOnSaleTo = dateOnSaleTo;
    return this;
  }

  /**
   * End date of sale price, in the site&#39;s timezone.
   * @return dateOnSaleTo
   */
  @javax.annotation.Nullable
  public String getDateOnSaleTo() {
    return dateOnSaleTo;
  }

  public void setDateOnSaleTo(@javax.annotation.Nullable String dateOnSaleTo) {
    this.dateOnSaleTo = dateOnSaleTo;
  }


  public WooCommerceWcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues dateOnSaleToGmt(@javax.annotation.Nullable String dateOnSaleToGmt) {
    this.dateOnSaleToGmt = dateOnSaleToGmt;
    return this;
  }

  /**
   * End date of sale price, in the site&#39;s timezone.
   * @return dateOnSaleToGmt
   */
  @javax.annotation.Nullable
  public String getDateOnSaleToGmt() {
    return dateOnSaleToGmt;
  }

  public void setDateOnSaleToGmt(@javax.annotation.Nullable String dateOnSaleToGmt) {
    this.dateOnSaleToGmt = dateOnSaleToGmt;
  }


  public WooCommerceWcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues status(@javax.annotation.Nullable StatusEnum status) {
    this.status = status;
    return this;
  }

  /**
   * Variation status.
   * @return status
   */
  @javax.annotation.Nullable
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(@javax.annotation.Nullable StatusEnum status) {
    this.status = status;
  }


  public WooCommerceWcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues virtual(@javax.annotation.Nullable Boolean virtual) {
    this.virtual = virtual;
    return this;
  }

  /**
   * If the variation is virtual.
   * @return virtual
   */
  @javax.annotation.Nullable
  public Boolean getVirtual() {
    return virtual;
  }

  public void setVirtual(@javax.annotation.Nullable Boolean virtual) {
    this.virtual = virtual;
  }


  public WooCommerceWcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues downloadable(@javax.annotation.Nullable Boolean downloadable) {
    this.downloadable = downloadable;
    return this;
  }

  /**
   * If the variation is downloadable.
   * @return downloadable
   */
  @javax.annotation.Nullable
  public Boolean getDownloadable() {
    return downloadable;
  }

  public void setDownloadable(@javax.annotation.Nullable Boolean downloadable) {
    this.downloadable = downloadable;
  }


  public WooCommerceWcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues downloads(@javax.annotation.Nullable List<WooCommerceWcV3ProductsPostRequestDownloadsInner> downloads) {
    this.downloads = downloads;
    return this;
  }

  public WooCommerceWcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues addDownloadsItem(WooCommerceWcV3ProductsPostRequestDownloadsInner downloadsItem) {
    if (this.downloads == null) {
      this.downloads = new ArrayList<>();
    }
    this.downloads.add(downloadsItem);
    return this;
  }

  /**
   * List of downloadable files.
   * @return downloads
   */
  @javax.annotation.Nullable
  public List<WooCommerceWcV3ProductsPostRequestDownloadsInner> getDownloads() {
    return downloads;
  }

  public void setDownloads(@javax.annotation.Nullable List<WooCommerceWcV3ProductsPostRequestDownloadsInner> downloads) {
    this.downloads = downloads;
  }


  public WooCommerceWcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues downloadLimit(@javax.annotation.Nullable Integer downloadLimit) {
    this.downloadLimit = downloadLimit;
    return this;
  }

  /**
   * Number of times downloadable files can be downloaded after purchase.
   * @return downloadLimit
   */
  @javax.annotation.Nullable
  public Integer getDownloadLimit() {
    return downloadLimit;
  }

  public void setDownloadLimit(@javax.annotation.Nullable Integer downloadLimit) {
    this.downloadLimit = downloadLimit;
  }


  public WooCommerceWcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues downloadExpiry(@javax.annotation.Nullable Integer downloadExpiry) {
    this.downloadExpiry = downloadExpiry;
    return this;
  }

  /**
   * Number of days until access to downloadable files expires.
   * @return downloadExpiry
   */
  @javax.annotation.Nullable
  public Integer getDownloadExpiry() {
    return downloadExpiry;
  }

  public void setDownloadExpiry(@javax.annotation.Nullable Integer downloadExpiry) {
    this.downloadExpiry = downloadExpiry;
  }


  public WooCommerceWcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues taxStatus(@javax.annotation.Nullable TaxStatusEnum taxStatus) {
    this.taxStatus = taxStatus;
    return this;
  }

  /**
   * Tax status.
   * @return taxStatus
   */
  @javax.annotation.Nullable
  public TaxStatusEnum getTaxStatus() {
    return taxStatus;
  }

  public void setTaxStatus(@javax.annotation.Nullable TaxStatusEnum taxStatus) {
    this.taxStatus = taxStatus;
  }


  public WooCommerceWcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues taxClass(@javax.annotation.Nullable String taxClass) {
    this.taxClass = taxClass;
    return this;
  }

  /**
   * Tax class.
   * @return taxClass
   */
  @javax.annotation.Nullable
  public String getTaxClass() {
    return taxClass;
  }

  public void setTaxClass(@javax.annotation.Nullable String taxClass) {
    this.taxClass = taxClass;
  }


  public WooCommerceWcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues manageStock(@javax.annotation.Nullable WooCommerceWcV3ProductsProductIdVariationsGeneratePostRequestDefaultValuesManageStock manageStock) {
    this.manageStock = manageStock;
    return this;
  }

  /**
   * Get manageStock
   * @return manageStock
   */
  @javax.annotation.Nullable
  public WooCommerceWcV3ProductsProductIdVariationsGeneratePostRequestDefaultValuesManageStock getManageStock() {
    return manageStock;
  }

  public void setManageStock(@javax.annotation.Nullable WooCommerceWcV3ProductsProductIdVariationsGeneratePostRequestDefaultValuesManageStock manageStock) {
    this.manageStock = manageStock;
  }


  public WooCommerceWcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues stockQuantity(@javax.annotation.Nullable Integer stockQuantity) {
    this.stockQuantity = stockQuantity;
    return this;
  }

  /**
   * Stock quantity.
   * @return stockQuantity
   */
  @javax.annotation.Nullable
  public Integer getStockQuantity() {
    return stockQuantity;
  }

  public void setStockQuantity(@javax.annotation.Nullable Integer stockQuantity) {
    this.stockQuantity = stockQuantity;
  }


  public WooCommerceWcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues stockStatus(@javax.annotation.Nullable StockStatusEnum stockStatus) {
    this.stockStatus = stockStatus;
    return this;
  }

  /**
   * Controls the stock status of the product.
   * @return stockStatus
   */
  @javax.annotation.Nullable
  public StockStatusEnum getStockStatus() {
    return stockStatus;
  }

  public void setStockStatus(@javax.annotation.Nullable StockStatusEnum stockStatus) {
    this.stockStatus = stockStatus;
  }


  public WooCommerceWcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues backorders(@javax.annotation.Nullable BackordersEnum backorders) {
    this.backorders = backorders;
    return this;
  }

  /**
   * If managing stock, this controls if backorders are allowed.
   * @return backorders
   */
  @javax.annotation.Nullable
  public BackordersEnum getBackorders() {
    return backorders;
  }

  public void setBackorders(@javax.annotation.Nullable BackordersEnum backorders) {
    this.backorders = backorders;
  }


  public WooCommerceWcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues lowStockAmount(@javax.annotation.Nullable Integer lowStockAmount) {
    this.lowStockAmount = lowStockAmount;
    return this;
  }

  /**
   * Low Stock amount for the variation.
   * @return lowStockAmount
   */
  @javax.annotation.Nullable
  public Integer getLowStockAmount() {
    return lowStockAmount;
  }

  public void setLowStockAmount(@javax.annotation.Nullable Integer lowStockAmount) {
    this.lowStockAmount = lowStockAmount;
  }


  public WooCommerceWcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues weight(@javax.annotation.Nullable String weight) {
    this.weight = weight;
    return this;
  }

  /**
   * Variation weight (lbs).
   * @return weight
   */
  @javax.annotation.Nullable
  public String getWeight() {
    return weight;
  }

  public void setWeight(@javax.annotation.Nullable String weight) {
    this.weight = weight;
  }


  public WooCommerceWcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues dimensions(@javax.annotation.Nullable WooCommerceWcV3ProductsProductIdVariationsGeneratePostRequestDefaultValuesDimensions dimensions) {
    this.dimensions = dimensions;
    return this;
  }

  /**
   * Get dimensions
   * @return dimensions
   */
  @javax.annotation.Nullable
  public WooCommerceWcV3ProductsProductIdVariationsGeneratePostRequestDefaultValuesDimensions getDimensions() {
    return dimensions;
  }

  public void setDimensions(@javax.annotation.Nullable WooCommerceWcV3ProductsProductIdVariationsGeneratePostRequestDefaultValuesDimensions dimensions) {
    this.dimensions = dimensions;
  }


  public WooCommerceWcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues shippingClass(@javax.annotation.Nullable String shippingClass) {
    this.shippingClass = shippingClass;
    return this;
  }

  /**
   * Shipping class slug.
   * @return shippingClass
   */
  @javax.annotation.Nullable
  public String getShippingClass() {
    return shippingClass;
  }

  public void setShippingClass(@javax.annotation.Nullable String shippingClass) {
    this.shippingClass = shippingClass;
  }


  public WooCommerceWcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues image(@javax.annotation.Nullable WooCommerceWcV3ProductsProductIdVariationsGeneratePostRequestDefaultValuesImage image) {
    this.image = image;
    return this;
  }

  /**
   * Get image
   * @return image
   */
  @javax.annotation.Nullable
  public WooCommerceWcV3ProductsProductIdVariationsGeneratePostRequestDefaultValuesImage getImage() {
    return image;
  }

  public void setImage(@javax.annotation.Nullable WooCommerceWcV3ProductsProductIdVariationsGeneratePostRequestDefaultValuesImage image) {
    this.image = image;
  }


  public WooCommerceWcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues attributes(@javax.annotation.Nullable List<WooCommerceWcV3ProductsPostRequestDefaultAttributesInner> attributes) {
    this.attributes = attributes;
    return this;
  }

  public WooCommerceWcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues addAttributesItem(WooCommerceWcV3ProductsPostRequestDefaultAttributesInner attributesItem) {
    if (this.attributes == null) {
      this.attributes = new ArrayList<>();
    }
    this.attributes.add(attributesItem);
    return this;
  }

  /**
   * List of attributes.
   * @return attributes
   */
  @javax.annotation.Nullable
  public List<WooCommerceWcV3ProductsPostRequestDefaultAttributesInner> getAttributes() {
    return attributes;
  }

  public void setAttributes(@javax.annotation.Nullable List<WooCommerceWcV3ProductsPostRequestDefaultAttributesInner> attributes) {
    this.attributes = attributes;
  }


  public WooCommerceWcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues menuOrder(@javax.annotation.Nullable Integer menuOrder) {
    this.menuOrder = menuOrder;
    return this;
  }

  /**
   * Menu order, used to custom sort products.
   * @return menuOrder
   */
  @javax.annotation.Nullable
  public Integer getMenuOrder() {
    return menuOrder;
  }

  public void setMenuOrder(@javax.annotation.Nullable Integer menuOrder) {
    this.menuOrder = menuOrder;
  }


  public WooCommerceWcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues metaData(@javax.annotation.Nullable List<WooCommerceWcV3CouponsPostRequestMetaDataInner> metaData) {
    this.metaData = metaData;
    return this;
  }

  public WooCommerceWcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues addMetaDataItem(WooCommerceWcV3CouponsPostRequestMetaDataInner metaDataItem) {
    if (this.metaData == null) {
      this.metaData = new ArrayList<>();
    }
    this.metaData.add(metaDataItem);
    return this;
  }

  /**
   * Meta data.
   * @return metaData
   */
  @javax.annotation.Nullable
  public List<WooCommerceWcV3CouponsPostRequestMetaDataInner> getMetaData() {
    return metaData;
  }

  public void setMetaData(@javax.annotation.Nullable List<WooCommerceWcV3CouponsPostRequestMetaDataInner> metaData) {
    this.metaData = metaData;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the WooCommerceWcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues instance itself
   */
  public WooCommerceWcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WooCommerceWcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues wcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues = (WooCommerceWcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues) o;
    return Objects.equals(this.description, wcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues.description) &&
        Objects.equals(this.sku, wcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues.sku) &&
        Objects.equals(this.globalUniqueId, wcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues.globalUniqueId) &&
        Objects.equals(this.regularPrice, wcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues.regularPrice) &&
        Objects.equals(this.salePrice, wcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues.salePrice) &&
        Objects.equals(this.dateOnSaleFrom, wcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues.dateOnSaleFrom) &&
        Objects.equals(this.dateOnSaleFromGmt, wcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues.dateOnSaleFromGmt) &&
        Objects.equals(this.dateOnSaleTo, wcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues.dateOnSaleTo) &&
        Objects.equals(this.dateOnSaleToGmt, wcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues.dateOnSaleToGmt) &&
        Objects.equals(this.status, wcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues.status) &&
        Objects.equals(this.virtual, wcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues.virtual) &&
        Objects.equals(this.downloadable, wcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues.downloadable) &&
        Objects.equals(this.downloads, wcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues.downloads) &&
        Objects.equals(this.downloadLimit, wcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues.downloadLimit) &&
        Objects.equals(this.downloadExpiry, wcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues.downloadExpiry) &&
        Objects.equals(this.taxStatus, wcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues.taxStatus) &&
        Objects.equals(this.taxClass, wcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues.taxClass) &&
        Objects.equals(this.manageStock, wcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues.manageStock) &&
        Objects.equals(this.stockQuantity, wcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues.stockQuantity) &&
        Objects.equals(this.stockStatus, wcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues.stockStatus) &&
        Objects.equals(this.backorders, wcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues.backorders) &&
        Objects.equals(this.lowStockAmount, wcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues.lowStockAmount) &&
        Objects.equals(this.weight, wcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues.weight) &&
        Objects.equals(this.dimensions, wcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues.dimensions) &&
        Objects.equals(this.shippingClass, wcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues.shippingClass) &&
        Objects.equals(this.image, wcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues.image) &&
        Objects.equals(this.attributes, wcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues.attributes) &&
        Objects.equals(this.menuOrder, wcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues.menuOrder) &&
        Objects.equals(this.metaData, wcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues.metaData)&&
        Objects.equals(this.additionalProperties, wcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues.additionalProperties);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, sku, globalUniqueId, regularPrice, salePrice, dateOnSaleFrom, dateOnSaleFromGmt, dateOnSaleTo, dateOnSaleToGmt, status, virtual, downloadable, downloads, downloadLimit, downloadExpiry, taxStatus, taxClass, manageStock, stockQuantity, stockStatus, backorders, lowStockAmount, weight, dimensions, shippingClass, image, attributes, menuOrder, metaData, additionalProperties);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WooCommerceWcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues {\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    sku: ").append(toIndentedString(sku)).append("\n");
    sb.append("    globalUniqueId: ").append(toIndentedString(globalUniqueId)).append("\n");
    sb.append("    regularPrice: ").append(toIndentedString(regularPrice)).append("\n");
    sb.append("    salePrice: ").append(toIndentedString(salePrice)).append("\n");
    sb.append("    dateOnSaleFrom: ").append(toIndentedString(dateOnSaleFrom)).append("\n");
    sb.append("    dateOnSaleFromGmt: ").append(toIndentedString(dateOnSaleFromGmt)).append("\n");
    sb.append("    dateOnSaleTo: ").append(toIndentedString(dateOnSaleTo)).append("\n");
    sb.append("    dateOnSaleToGmt: ").append(toIndentedString(dateOnSaleToGmt)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    virtual: ").append(toIndentedString(virtual)).append("\n");
    sb.append("    downloadable: ").append(toIndentedString(downloadable)).append("\n");
    sb.append("    downloads: ").append(toIndentedString(downloads)).append("\n");
    sb.append("    downloadLimit: ").append(toIndentedString(downloadLimit)).append("\n");
    sb.append("    downloadExpiry: ").append(toIndentedString(downloadExpiry)).append("\n");
    sb.append("    taxStatus: ").append(toIndentedString(taxStatus)).append("\n");
    sb.append("    taxClass: ").append(toIndentedString(taxClass)).append("\n");
    sb.append("    manageStock: ").append(toIndentedString(manageStock)).append("\n");
    sb.append("    stockQuantity: ").append(toIndentedString(stockQuantity)).append("\n");
    sb.append("    stockStatus: ").append(toIndentedString(stockStatus)).append("\n");
    sb.append("    backorders: ").append(toIndentedString(backorders)).append("\n");
    sb.append("    lowStockAmount: ").append(toIndentedString(lowStockAmount)).append("\n");
    sb.append("    weight: ").append(toIndentedString(weight)).append("\n");
    sb.append("    dimensions: ").append(toIndentedString(dimensions)).append("\n");
    sb.append("    shippingClass: ").append(toIndentedString(shippingClass)).append("\n");
    sb.append("    image: ").append(toIndentedString(image)).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("    menuOrder: ").append(toIndentedString(menuOrder)).append("\n");
    sb.append("    metaData: ").append(toIndentedString(metaData)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("description", "sku", "global_unique_id", "regular_price", "sale_price", "date_on_sale_from", "date_on_sale_from_gmt", "date_on_sale_to", "date_on_sale_to_gmt", "status", "virtual", "downloadable", "downloads", "download_limit", "download_expiry", "tax_status", "tax_class", "manage_stock", "stock_quantity", "stock_status", "backorders", "low_stock_amount", "weight", "dimensions", "shipping_class", "image", "attributes", "menu_order", "meta_data"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to WooCommerceWcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!WooCommerceWcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in WooCommerceWcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues is not found in the empty JSON string", WooCommerceWcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues.openapiRequiredFields.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("description") != null && !jsonObj.get("description").isJsonNull()) && !jsonObj.get("description").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `description` to be a primitive type in the JSON string but got `%s`", jsonObj.get("description").toString()));
      }
      if ((jsonObj.get("sku") != null && !jsonObj.get("sku").isJsonNull()) && !jsonObj.get("sku").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `sku` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sku").toString()));
      }
      if ((jsonObj.get("global_unique_id") != null && !jsonObj.get("global_unique_id").isJsonNull()) && !jsonObj.get("global_unique_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `global_unique_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("global_unique_id").toString()));
      }
      if ((jsonObj.get("regular_price") != null && !jsonObj.get("regular_price").isJsonNull()) && !jsonObj.get("regular_price").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `regular_price` to be a primitive type in the JSON string but got `%s`", jsonObj.get("regular_price").toString()));
      }
      if ((jsonObj.get("sale_price") != null && !jsonObj.get("sale_price").isJsonNull()) && !jsonObj.get("sale_price").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `sale_price` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sale_price").toString()));
      }
      if ((jsonObj.get("date_on_sale_from") != null && !jsonObj.get("date_on_sale_from").isJsonNull()) && !jsonObj.get("date_on_sale_from").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `date_on_sale_from` to be a primitive type in the JSON string but got `%s`", jsonObj.get("date_on_sale_from").toString()));
      }
      if ((jsonObj.get("date_on_sale_from_gmt") != null && !jsonObj.get("date_on_sale_from_gmt").isJsonNull()) && !jsonObj.get("date_on_sale_from_gmt").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `date_on_sale_from_gmt` to be a primitive type in the JSON string but got `%s`", jsonObj.get("date_on_sale_from_gmt").toString()));
      }
      if ((jsonObj.get("date_on_sale_to") != null && !jsonObj.get("date_on_sale_to").isJsonNull()) && !jsonObj.get("date_on_sale_to").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `date_on_sale_to` to be a primitive type in the JSON string but got `%s`", jsonObj.get("date_on_sale_to").toString()));
      }
      if ((jsonObj.get("date_on_sale_to_gmt") != null && !jsonObj.get("date_on_sale_to_gmt").isJsonNull()) && !jsonObj.get("date_on_sale_to_gmt").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `date_on_sale_to_gmt` to be a primitive type in the JSON string but got `%s`", jsonObj.get("date_on_sale_to_gmt").toString()));
      }
      if ((jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) && !jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
      // validate the optional field `status`
      if (jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) {
        StatusEnum.validateJsonElement(jsonObj.get("status"));
      }
      if (jsonObj.get("downloads") != null && !jsonObj.get("downloads").isJsonNull()) {
        JsonArray jsonArraydownloads = jsonObj.getAsJsonArray("downloads");
        if (jsonArraydownloads != null) {
          // ensure the json data is an array
          if (!jsonObj.get("downloads").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `downloads` to be an array in the JSON string but got `%s`", jsonObj.get("downloads").toString()));
          }

          // validate the optional field `downloads` (array)
          for (int i = 0; i < jsonArraydownloads.size(); i++) {
            WooCommerceWcV3ProductsPostRequestDownloadsInner.validateJsonElement(jsonArraydownloads.get(i));
          };
        }
      }
      if ((jsonObj.get("tax_status") != null && !jsonObj.get("tax_status").isJsonNull()) && !jsonObj.get("tax_status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `tax_status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("tax_status").toString()));
      }
      // validate the optional field `tax_status`
      if (jsonObj.get("tax_status") != null && !jsonObj.get("tax_status").isJsonNull()) {
        TaxStatusEnum.validateJsonElement(jsonObj.get("tax_status"));
      }
      if ((jsonObj.get("tax_class") != null && !jsonObj.get("tax_class").isJsonNull()) && !jsonObj.get("tax_class").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `tax_class` to be a primitive type in the JSON string but got `%s`", jsonObj.get("tax_class").toString()));
      }
      // validate the optional field `manage_stock`
      if (jsonObj.get("manage_stock") != null && !jsonObj.get("manage_stock").isJsonNull()) {
        WooCommerceWcV3ProductsProductIdVariationsGeneratePostRequestDefaultValuesManageStock.validateJsonElement(jsonObj.get("manage_stock"));
      }
      if ((jsonObj.get("stock_status") != null && !jsonObj.get("stock_status").isJsonNull()) && !jsonObj.get("stock_status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `stock_status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("stock_status").toString()));
      }
      // validate the optional field `stock_status`
      if (jsonObj.get("stock_status") != null && !jsonObj.get("stock_status").isJsonNull()) {
        StockStatusEnum.validateJsonElement(jsonObj.get("stock_status"));
      }
      if ((jsonObj.get("backorders") != null && !jsonObj.get("backorders").isJsonNull()) && !jsonObj.get("backorders").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `backorders` to be a primitive type in the JSON string but got `%s`", jsonObj.get("backorders").toString()));
      }
      // validate the optional field `backorders`
      if (jsonObj.get("backorders") != null && !jsonObj.get("backorders").isJsonNull()) {
        BackordersEnum.validateJsonElement(jsonObj.get("backorders"));
      }
      if ((jsonObj.get("weight") != null && !jsonObj.get("weight").isJsonNull()) && !jsonObj.get("weight").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `weight` to be a primitive type in the JSON string but got `%s`", jsonObj.get("weight").toString()));
      }
      // validate the optional field `dimensions`
      if (jsonObj.get("dimensions") != null && !jsonObj.get("dimensions").isJsonNull()) {
        WooCommerceWcV3ProductsProductIdVariationsGeneratePostRequestDefaultValuesDimensions.validateJsonElement(jsonObj.get("dimensions"));
      }
      if ((jsonObj.get("shipping_class") != null && !jsonObj.get("shipping_class").isJsonNull()) && !jsonObj.get("shipping_class").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `shipping_class` to be a primitive type in the JSON string but got `%s`", jsonObj.get("shipping_class").toString()));
      }
      // validate the optional field `image`
      if (jsonObj.get("image") != null && !jsonObj.get("image").isJsonNull()) {
        WooCommerceWcV3ProductsProductIdVariationsGeneratePostRequestDefaultValuesImage.validateJsonElement(jsonObj.get("image"));
      }
      if (jsonObj.get("attributes") != null && !jsonObj.get("attributes").isJsonNull()) {
        JsonArray jsonArrayattributes = jsonObj.getAsJsonArray("attributes");
        if (jsonArrayattributes != null) {
          // ensure the json data is an array
          if (!jsonObj.get("attributes").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `attributes` to be an array in the JSON string but got `%s`", jsonObj.get("attributes").toString()));
          }

          // validate the optional field `attributes` (array)
          for (int i = 0; i < jsonArrayattributes.size(); i++) {
            WooCommerceWcV3ProductsPostRequestDefaultAttributesInner.validateJsonElement(jsonArrayattributes.get(i));
          };
        }
      }
      if (jsonObj.get("meta_data") != null && !jsonObj.get("meta_data").isJsonNull()) {
        JsonArray jsonArraymetaData = jsonObj.getAsJsonArray("meta_data");
        if (jsonArraymetaData != null) {
          // ensure the json data is an array
          if (!jsonObj.get("meta_data").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `meta_data` to be an array in the JSON string but got `%s`", jsonObj.get("meta_data").toString()));
          }

          // validate the optional field `meta_data` (array)
          for (int i = 0; i < jsonArraymetaData.size(); i++) {
            WooCommerceWcV3CouponsPostRequestMetaDataInner.validateJsonElement(jsonArraymetaData.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!WooCommerceWcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'WooCommerceWcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<WooCommerceWcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(WooCommerceWcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues.class));

       return (TypeAdapter<T>) new TypeAdapter<WooCommerceWcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues>() {
           @Override
           public void write(JsonWriter out, WooCommerceWcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public WooCommerceWcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             WooCommerceWcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of WooCommerceWcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of WooCommerceWcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues
   * @throws IOException if the JSON string is invalid with respect to WooCommerceWcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues
   */
  public static WooCommerceWcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, WooCommerceWcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues.class);
  }

  /**
   * Convert an instance of WooCommerceWcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

