/*
 * Dev Store API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.9.1
 * Contact: admin@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.woocommerce.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.woocommerce.model.WooCommerceShopCouponMetaDataInner;
import com.woocommerce.model.WooCommerceShopOrderRefundFeeLinesInner;
import com.woocommerce.model.WooCommerceShopOrderRefundLineItemsInner;
import com.woocommerce.model.WooCommerceShopOrderRefundShippingLinesInner;
import com.woocommerce.model.WooCommerceShopOrderRefundTaxLinesInner;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.woocommerce.JSON;

/**
 * WooCommerceShopOrderRefund
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.20.0-SNAPSHOT")
public class WooCommerceShopOrderRefund {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private Integer id;

  public static final String SERIALIZED_NAME_PARENT_ID = "parent_id";
  @SerializedName(SERIALIZED_NAME_PARENT_ID)
  @javax.annotation.Nullable
  private Integer parentId;

  public static final String SERIALIZED_NAME_DATE_CREATED = "date_created";
  @SerializedName(SERIALIZED_NAME_DATE_CREATED)
  @javax.annotation.Nullable
  private OffsetDateTime dateCreated;

  public static final String SERIALIZED_NAME_DATE_CREATED_GMT = "date_created_gmt";
  @SerializedName(SERIALIZED_NAME_DATE_CREATED_GMT)
  @javax.annotation.Nullable
  private OffsetDateTime dateCreatedGmt;

  public static final String SERIALIZED_NAME_AMOUNT = "amount";
  @SerializedName(SERIALIZED_NAME_AMOUNT)
  @javax.annotation.Nullable
  private String amount;

  public static final String SERIALIZED_NAME_REASON = "reason";
  @SerializedName(SERIALIZED_NAME_REASON)
  @javax.annotation.Nullable
  private String reason;

  public static final String SERIALIZED_NAME_REFUNDED_BY = "refunded_by";
  @SerializedName(SERIALIZED_NAME_REFUNDED_BY)
  @javax.annotation.Nullable
  private Integer refundedBy;

  public static final String SERIALIZED_NAME_REFUNDED_PAYMENT = "refunded_payment";
  @SerializedName(SERIALIZED_NAME_REFUNDED_PAYMENT)
  @javax.annotation.Nullable
  private Boolean refundedPayment;

  public static final String SERIALIZED_NAME_META_DATA = "meta_data";
  @SerializedName(SERIALIZED_NAME_META_DATA)
  @javax.annotation.Nullable
  private List<WooCommerceShopCouponMetaDataInner> metaData = new ArrayList<>();

  public static final String SERIALIZED_NAME_LINE_ITEMS = "line_items";
  @SerializedName(SERIALIZED_NAME_LINE_ITEMS)
  @javax.annotation.Nullable
  private List<WooCommerceShopOrderRefundLineItemsInner> lineItems = new ArrayList<>();

  public static final String SERIALIZED_NAME_TAX_LINES = "tax_lines";
  @SerializedName(SERIALIZED_NAME_TAX_LINES)
  @javax.annotation.Nullable
  private List<WooCommerceShopOrderRefundTaxLinesInner> taxLines = new ArrayList<>();

  public static final String SERIALIZED_NAME_SHIPPING_LINES = "shipping_lines";
  @SerializedName(SERIALIZED_NAME_SHIPPING_LINES)
  @javax.annotation.Nullable
  private List<WooCommerceShopOrderRefundShippingLinesInner> shippingLines = new ArrayList<>();

  public static final String SERIALIZED_NAME_FEE_LINES = "fee_lines";
  @SerializedName(SERIALIZED_NAME_FEE_LINES)
  @javax.annotation.Nullable
  private List<WooCommerceShopOrderRefundFeeLinesInner> feeLines = new ArrayList<>();

  public static final String SERIALIZED_NAME_API_REFUND = "api_refund";
  @SerializedName(SERIALIZED_NAME_API_REFUND)
  @javax.annotation.Nullable
  private Boolean apiRefund = true;

  public static final String SERIALIZED_NAME_API_RESTOCK = "api_restock";
  @SerializedName(SERIALIZED_NAME_API_RESTOCK)
  @javax.annotation.Nullable
  private Boolean apiRestock = true;

  public WooCommerceShopOrderRefund() {
  }

  public WooCommerceShopOrderRefund id(@javax.annotation.Nullable Integer id) {
    this.id = id;
    return this;
  }

  /**
   * Unique identifier for the resource.
   * @return id
   */
  @javax.annotation.Nullable
  public Integer getId() {
    return id;
  }

  public void setId(@javax.annotation.Nullable Integer id) {
    this.id = id;
  }


  public WooCommerceShopOrderRefund parentId(@javax.annotation.Nullable Integer parentId) {
    this.parentId = parentId;
    return this;
  }

  /**
   * Parent order ID.
   * @return parentId
   */
  @javax.annotation.Nullable
  public Integer getParentId() {
    return parentId;
  }

  public void setParentId(@javax.annotation.Nullable Integer parentId) {
    this.parentId = parentId;
  }


  public WooCommerceShopOrderRefund dateCreated(@javax.annotation.Nullable OffsetDateTime dateCreated) {
    this.dateCreated = dateCreated;
    return this;
  }

  /**
   * The date the order refund was created, in the site&#39;s timezone.
   * @return dateCreated
   */
  @javax.annotation.Nullable
  public OffsetDateTime getDateCreated() {
    return dateCreated;
  }

  public void setDateCreated(@javax.annotation.Nullable OffsetDateTime dateCreated) {
    this.dateCreated = dateCreated;
  }


  public WooCommerceShopOrderRefund dateCreatedGmt(@javax.annotation.Nullable OffsetDateTime dateCreatedGmt) {
    this.dateCreatedGmt = dateCreatedGmt;
    return this;
  }

  /**
   * The date the order refund was created, as GMT.
   * @return dateCreatedGmt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getDateCreatedGmt() {
    return dateCreatedGmt;
  }

  public void setDateCreatedGmt(@javax.annotation.Nullable OffsetDateTime dateCreatedGmt) {
    this.dateCreatedGmt = dateCreatedGmt;
  }


  public WooCommerceShopOrderRefund amount(@javax.annotation.Nullable String amount) {
    this.amount = amount;
    return this;
  }

  /**
   * Refund amount.
   * @return amount
   */
  @javax.annotation.Nullable
  public String getAmount() {
    return amount;
  }

  public void setAmount(@javax.annotation.Nullable String amount) {
    this.amount = amount;
  }


  public WooCommerceShopOrderRefund reason(@javax.annotation.Nullable String reason) {
    this.reason = reason;
    return this;
  }

  /**
   * Reason for refund.
   * @return reason
   */
  @javax.annotation.Nullable
  public String getReason() {
    return reason;
  }

  public void setReason(@javax.annotation.Nullable String reason) {
    this.reason = reason;
  }


  public WooCommerceShopOrderRefund refundedBy(@javax.annotation.Nullable Integer refundedBy) {
    this.refundedBy = refundedBy;
    return this;
  }

  /**
   * User ID of user who created the refund.
   * @return refundedBy
   */
  @javax.annotation.Nullable
  public Integer getRefundedBy() {
    return refundedBy;
  }

  public void setRefundedBy(@javax.annotation.Nullable Integer refundedBy) {
    this.refundedBy = refundedBy;
  }


  public WooCommerceShopOrderRefund refundedPayment(@javax.annotation.Nullable Boolean refundedPayment) {
    this.refundedPayment = refundedPayment;
    return this;
  }

  /**
   * If the payment was refunded via the API.
   * @return refundedPayment
   */
  @javax.annotation.Nullable
  public Boolean getRefundedPayment() {
    return refundedPayment;
  }

  public void setRefundedPayment(@javax.annotation.Nullable Boolean refundedPayment) {
    this.refundedPayment = refundedPayment;
  }


  public WooCommerceShopOrderRefund metaData(@javax.annotation.Nullable List<WooCommerceShopCouponMetaDataInner> metaData) {
    this.metaData = metaData;
    return this;
  }

  public WooCommerceShopOrderRefund addMetaDataItem(WooCommerceShopCouponMetaDataInner metaDataItem) {
    if (this.metaData == null) {
      this.metaData = new ArrayList<>();
    }
    this.metaData.add(metaDataItem);
    return this;
  }

  /**
   * Meta data.
   * @return metaData
   */
  @javax.annotation.Nullable
  public List<WooCommerceShopCouponMetaDataInner> getMetaData() {
    return metaData;
  }

  public void setMetaData(@javax.annotation.Nullable List<WooCommerceShopCouponMetaDataInner> metaData) {
    this.metaData = metaData;
  }


  public WooCommerceShopOrderRefund lineItems(@javax.annotation.Nullable List<WooCommerceShopOrderRefundLineItemsInner> lineItems) {
    this.lineItems = lineItems;
    return this;
  }

  public WooCommerceShopOrderRefund addLineItemsItem(WooCommerceShopOrderRefundLineItemsInner lineItemsItem) {
    if (this.lineItems == null) {
      this.lineItems = new ArrayList<>();
    }
    this.lineItems.add(lineItemsItem);
    return this;
  }

  /**
   * Line items data.
   * @return lineItems
   */
  @javax.annotation.Nullable
  public List<WooCommerceShopOrderRefundLineItemsInner> getLineItems() {
    return lineItems;
  }

  public void setLineItems(@javax.annotation.Nullable List<WooCommerceShopOrderRefundLineItemsInner> lineItems) {
    this.lineItems = lineItems;
  }


  public WooCommerceShopOrderRefund taxLines(@javax.annotation.Nullable List<WooCommerceShopOrderRefundTaxLinesInner> taxLines) {
    this.taxLines = taxLines;
    return this;
  }

  public WooCommerceShopOrderRefund addTaxLinesItem(WooCommerceShopOrderRefundTaxLinesInner taxLinesItem) {
    if (this.taxLines == null) {
      this.taxLines = new ArrayList<>();
    }
    this.taxLines.add(taxLinesItem);
    return this;
  }

  /**
   * Tax lines data.
   * @return taxLines
   */
  @javax.annotation.Nullable
  public List<WooCommerceShopOrderRefundTaxLinesInner> getTaxLines() {
    return taxLines;
  }

  public void setTaxLines(@javax.annotation.Nullable List<WooCommerceShopOrderRefundTaxLinesInner> taxLines) {
    this.taxLines = taxLines;
  }


  public WooCommerceShopOrderRefund shippingLines(@javax.annotation.Nullable List<WooCommerceShopOrderRefundShippingLinesInner> shippingLines) {
    this.shippingLines = shippingLines;
    return this;
  }

  public WooCommerceShopOrderRefund addShippingLinesItem(WooCommerceShopOrderRefundShippingLinesInner shippingLinesItem) {
    if (this.shippingLines == null) {
      this.shippingLines = new ArrayList<>();
    }
    this.shippingLines.add(shippingLinesItem);
    return this;
  }

  /**
   * Shipping lines data.
   * @return shippingLines
   */
  @javax.annotation.Nullable
  public List<WooCommerceShopOrderRefundShippingLinesInner> getShippingLines() {
    return shippingLines;
  }

  public void setShippingLines(@javax.annotation.Nullable List<WooCommerceShopOrderRefundShippingLinesInner> shippingLines) {
    this.shippingLines = shippingLines;
  }


  public WooCommerceShopOrderRefund feeLines(@javax.annotation.Nullable List<WooCommerceShopOrderRefundFeeLinesInner> feeLines) {
    this.feeLines = feeLines;
    return this;
  }

  public WooCommerceShopOrderRefund addFeeLinesItem(WooCommerceShopOrderRefundFeeLinesInner feeLinesItem) {
    if (this.feeLines == null) {
      this.feeLines = new ArrayList<>();
    }
    this.feeLines.add(feeLinesItem);
    return this;
  }

  /**
   * Fee lines data.
   * @return feeLines
   */
  @javax.annotation.Nullable
  public List<WooCommerceShopOrderRefundFeeLinesInner> getFeeLines() {
    return feeLines;
  }

  public void setFeeLines(@javax.annotation.Nullable List<WooCommerceShopOrderRefundFeeLinesInner> feeLines) {
    this.feeLines = feeLines;
  }


  public WooCommerceShopOrderRefund apiRefund(@javax.annotation.Nullable Boolean apiRefund) {
    this.apiRefund = apiRefund;
    return this;
  }

  /**
   * When true, the payment gateway API is used to generate the refund.
   * @return apiRefund
   */
  @javax.annotation.Nullable
  public Boolean getApiRefund() {
    return apiRefund;
  }

  public void setApiRefund(@javax.annotation.Nullable Boolean apiRefund) {
    this.apiRefund = apiRefund;
  }


  public WooCommerceShopOrderRefund apiRestock(@javax.annotation.Nullable Boolean apiRestock) {
    this.apiRestock = apiRestock;
    return this;
  }

  /**
   * When true, refunded items are restocked.
   * @return apiRestock
   */
  @javax.annotation.Nullable
  public Boolean getApiRestock() {
    return apiRestock;
  }

  public void setApiRestock(@javax.annotation.Nullable Boolean apiRestock) {
    this.apiRestock = apiRestock;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the WooCommerceShopOrderRefund instance itself
   */
  public WooCommerceShopOrderRefund putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WooCommerceShopOrderRefund shopOrderRefund = (WooCommerceShopOrderRefund) o;
    return Objects.equals(this.id, shopOrderRefund.id) &&
        Objects.equals(this.parentId, shopOrderRefund.parentId) &&
        Objects.equals(this.dateCreated, shopOrderRefund.dateCreated) &&
        Objects.equals(this.dateCreatedGmt, shopOrderRefund.dateCreatedGmt) &&
        Objects.equals(this.amount, shopOrderRefund.amount) &&
        Objects.equals(this.reason, shopOrderRefund.reason) &&
        Objects.equals(this.refundedBy, shopOrderRefund.refundedBy) &&
        Objects.equals(this.refundedPayment, shopOrderRefund.refundedPayment) &&
        Objects.equals(this.metaData, shopOrderRefund.metaData) &&
        Objects.equals(this.lineItems, shopOrderRefund.lineItems) &&
        Objects.equals(this.taxLines, shopOrderRefund.taxLines) &&
        Objects.equals(this.shippingLines, shopOrderRefund.shippingLines) &&
        Objects.equals(this.feeLines, shopOrderRefund.feeLines) &&
        Objects.equals(this.apiRefund, shopOrderRefund.apiRefund) &&
        Objects.equals(this.apiRestock, shopOrderRefund.apiRestock)&&
        Objects.equals(this.additionalProperties, shopOrderRefund.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, parentId, dateCreated, dateCreatedGmt, amount, reason, refundedBy, refundedPayment, metaData, lineItems, taxLines, shippingLines, feeLines, apiRefund, apiRestock, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WooCommerceShopOrderRefund {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    parentId: ").append(toIndentedString(parentId)).append("\n");
    sb.append("    dateCreated: ").append(toIndentedString(dateCreated)).append("\n");
    sb.append("    dateCreatedGmt: ").append(toIndentedString(dateCreatedGmt)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
    sb.append("    refundedBy: ").append(toIndentedString(refundedBy)).append("\n");
    sb.append("    refundedPayment: ").append(toIndentedString(refundedPayment)).append("\n");
    sb.append("    metaData: ").append(toIndentedString(metaData)).append("\n");
    sb.append("    lineItems: ").append(toIndentedString(lineItems)).append("\n");
    sb.append("    taxLines: ").append(toIndentedString(taxLines)).append("\n");
    sb.append("    shippingLines: ").append(toIndentedString(shippingLines)).append("\n");
    sb.append("    feeLines: ").append(toIndentedString(feeLines)).append("\n");
    sb.append("    apiRefund: ").append(toIndentedString(apiRefund)).append("\n");
    sb.append("    apiRestock: ").append(toIndentedString(apiRestock)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("id", "parent_id", "date_created", "date_created_gmt", "amount", "reason", "refunded_by", "refunded_payment", "meta_data", "line_items", "tax_lines", "shipping_lines", "fee_lines", "api_refund", "api_restock"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to WooCommerceShopOrderRefund
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!WooCommerceShopOrderRefund.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in WooCommerceShopOrderRefund is not found in the empty JSON string", WooCommerceShopOrderRefund.openapiRequiredFields.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("amount") != null && !jsonObj.get("amount").isJsonNull()) && !jsonObj.get("amount").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `amount` to be a primitive type in the JSON string but got `%s`", jsonObj.get("amount").toString()));
      }
      if ((jsonObj.get("reason") != null && !jsonObj.get("reason").isJsonNull()) && !jsonObj.get("reason").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `reason` to be a primitive type in the JSON string but got `%s`", jsonObj.get("reason").toString()));
      }
      if (jsonObj.get("meta_data") != null && !jsonObj.get("meta_data").isJsonNull()) {
        JsonArray jsonArraymetaData = jsonObj.getAsJsonArray("meta_data");
        if (jsonArraymetaData != null) {
          // ensure the json data is an array
          if (!jsonObj.get("meta_data").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `meta_data` to be an array in the JSON string but got `%s`", jsonObj.get("meta_data").toString()));
          }

          // validate the optional field `meta_data` (array)
          for (int i = 0; i < jsonArraymetaData.size(); i++) {
            WooCommerceShopCouponMetaDataInner.validateJsonElement(jsonArraymetaData.get(i));
          };
        }
      }
      if (jsonObj.get("line_items") != null && !jsonObj.get("line_items").isJsonNull()) {
        JsonArray jsonArraylineItems = jsonObj.getAsJsonArray("line_items");
        if (jsonArraylineItems != null) {
          // ensure the json data is an array
          if (!jsonObj.get("line_items").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `line_items` to be an array in the JSON string but got `%s`", jsonObj.get("line_items").toString()));
          }

          // validate the optional field `line_items` (array)
          for (int i = 0; i < jsonArraylineItems.size(); i++) {
            WooCommerceShopOrderRefundLineItemsInner.validateJsonElement(jsonArraylineItems.get(i));
          };
        }
      }
      if (jsonObj.get("tax_lines") != null && !jsonObj.get("tax_lines").isJsonNull()) {
        JsonArray jsonArraytaxLines = jsonObj.getAsJsonArray("tax_lines");
        if (jsonArraytaxLines != null) {
          // ensure the json data is an array
          if (!jsonObj.get("tax_lines").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `tax_lines` to be an array in the JSON string but got `%s`", jsonObj.get("tax_lines").toString()));
          }

          // validate the optional field `tax_lines` (array)
          for (int i = 0; i < jsonArraytaxLines.size(); i++) {
            WooCommerceShopOrderRefundTaxLinesInner.validateJsonElement(jsonArraytaxLines.get(i));
          };
        }
      }
      if (jsonObj.get("shipping_lines") != null && !jsonObj.get("shipping_lines").isJsonNull()) {
        JsonArray jsonArrayshippingLines = jsonObj.getAsJsonArray("shipping_lines");
        if (jsonArrayshippingLines != null) {
          // ensure the json data is an array
          if (!jsonObj.get("shipping_lines").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `shipping_lines` to be an array in the JSON string but got `%s`", jsonObj.get("shipping_lines").toString()));
          }

          // validate the optional field `shipping_lines` (array)
          for (int i = 0; i < jsonArrayshippingLines.size(); i++) {
            WooCommerceShopOrderRefundShippingLinesInner.validateJsonElement(jsonArrayshippingLines.get(i));
          };
        }
      }
      if (jsonObj.get("fee_lines") != null && !jsonObj.get("fee_lines").isJsonNull()) {
        JsonArray jsonArrayfeeLines = jsonObj.getAsJsonArray("fee_lines");
        if (jsonArrayfeeLines != null) {
          // ensure the json data is an array
          if (!jsonObj.get("fee_lines").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `fee_lines` to be an array in the JSON string but got `%s`", jsonObj.get("fee_lines").toString()));
          }

          // validate the optional field `fee_lines` (array)
          for (int i = 0; i < jsonArrayfeeLines.size(); i++) {
            WooCommerceShopOrderRefundFeeLinesInner.validateJsonElement(jsonArrayfeeLines.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!WooCommerceShopOrderRefund.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'WooCommerceShopOrderRefund' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<WooCommerceShopOrderRefund> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(WooCommerceShopOrderRefund.class));

       return (TypeAdapter<T>) new TypeAdapter<WooCommerceShopOrderRefund>() {
           @Override
           public void write(JsonWriter out, WooCommerceShopOrderRefund value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public WooCommerceShopOrderRefund read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             WooCommerceShopOrderRefund instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of WooCommerceShopOrderRefund given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of WooCommerceShopOrderRefund
   * @throws IOException if the JSON string is invalid with respect to WooCommerceShopOrderRefund
   */
  public static WooCommerceShopOrderRefund fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, WooCommerceShopOrderRefund.class);
  }

  /**
   * Convert an instance of WooCommerceShopOrderRefund to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

