/*
 * Dev Store API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.9.1
 * Contact: admin@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.woocommerce.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.woocommerce.model.WooCommerceShopCouponMetaDataInner;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for WooCommerceShopOrderCouponLinesInner
 */
public class WooCommerceShopOrderCouponLinesInnerTest {
    private final WooCommerceShopOrderCouponLinesInner model = new WooCommerceShopOrderCouponLinesInner();

    /**
     * Model tests for WooCommerceShopOrderCouponLinesInner
     */
    @Test
    public void testWooCommerceShopOrderCouponLinesInner() {
        // TODO: test WooCommerceShopOrderCouponLinesInner
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'code'
     */
    @Test
    public void codeTest() {
        // TODO: test code
    }

    /**
     * Test the property 'discount'
     */
    @Test
    public void discountTest() {
        // TODO: test discount
    }

    /**
     * Test the property 'discountTax'
     */
    @Test
    public void discountTaxTest() {
        // TODO: test discountTax
    }

    /**
     * Test the property 'discountType'
     */
    @Test
    public void discountTypeTest() {
        // TODO: test discountType
    }

    /**
     * Test the property 'nominalAmount'
     */
    @Test
    public void nominalAmountTest() {
        // TODO: test nominalAmount
    }

    /**
     * Test the property 'freeShipping'
     */
    @Test
    public void freeShippingTest() {
        // TODO: test freeShipping
    }

    /**
     * Test the property 'metaData'
     */
    @Test
    public void metaDataTest() {
        // TODO: test metaData
    }

}
