/*
 * Dev Store API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.9.1
 * Contact: admin@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.woocommerce.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.woocommerce.model.WooCommerceWcV3OrdersOrderIdRefundsPostRequestFeeLinesInnerTaxesInner;
import com.woocommerce.model.WooCommerceWcV3OrdersPostRequestLineItemsInnerImage;
import com.woocommerce.model.WooCommerceWcV3OrdersPostRequestLineItemsInnerMetaDataInner;
import com.woocommerce.model.WooCommerceWcV3OrdersPostRequestLineItemsInnerName;
import com.woocommerce.model.WooCommerceWcV3OrdersPostRequestLineItemsInnerProductId;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for WooCommerceWcV3OrdersPostRequestLineItemsInner
 */
public class WooCommerceWcV3OrdersPostRequestLineItemsInnerTest {
    private final WooCommerceWcV3OrdersPostRequestLineItemsInner model = new WooCommerceWcV3OrdersPostRequestLineItemsInner();

    /**
     * Model tests for WooCommerceWcV3OrdersPostRequestLineItemsInner
     */
    @Test
    public void testWooCommerceWcV3OrdersPostRequestLineItemsInner() {
        // TODO: test WooCommerceWcV3OrdersPostRequestLineItemsInner
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'parentName'
     */
    @Test
    public void parentNameTest() {
        // TODO: test parentName
    }

    /**
     * Test the property 'productId'
     */
    @Test
    public void productIdTest() {
        // TODO: test productId
    }

    /**
     * Test the property 'variationId'
     */
    @Test
    public void variationIdTest() {
        // TODO: test variationId
    }

    /**
     * Test the property 'quantity'
     */
    @Test
    public void quantityTest() {
        // TODO: test quantity
    }

    /**
     * Test the property 'taxClass'
     */
    @Test
    public void taxClassTest() {
        // TODO: test taxClass
    }

    /**
     * Test the property 'subtotal'
     */
    @Test
    public void subtotalTest() {
        // TODO: test subtotal
    }

    /**
     * Test the property 'subtotalTax'
     */
    @Test
    public void subtotalTaxTest() {
        // TODO: test subtotalTax
    }

    /**
     * Test the property 'total'
     */
    @Test
    public void totalTest() {
        // TODO: test total
    }

    /**
     * Test the property 'totalTax'
     */
    @Test
    public void totalTaxTest() {
        // TODO: test totalTax
    }

    /**
     * Test the property 'taxes'
     */
    @Test
    public void taxesTest() {
        // TODO: test taxes
    }

    /**
     * Test the property 'metaData'
     */
    @Test
    public void metaDataTest() {
        // TODO: test metaData
    }

    /**
     * Test the property 'sku'
     */
    @Test
    public void skuTest() {
        // TODO: test sku
    }

    /**
     * Test the property 'globalUniqueId'
     */
    @Test
    public void globalUniqueIdTest() {
        // TODO: test globalUniqueId
    }

    /**
     * Test the property 'price'
     */
    @Test
    public void priceTest() {
        // TODO: test price
    }

    /**
     * Test the property 'image'
     */
    @Test
    public void imageTest() {
        // TODO: test image
    }

}
