/*
 * Dev Store API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.9.1
 * Contact: admin@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.woocommerce.model;

import java.math.BigDecimal;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for WooCommerceWcV3OrdersOrderIdRefundsPostRequestShippingLinesInnerMethodId
 */
public class WooCommerceWcV3OrdersOrderIdRefundsPostRequestShippingLinesInnerMethodIdTest {
    private final WooCommerceWcV3OrdersOrderIdRefundsPostRequestShippingLinesInnerMethodId model = new WooCommerceWcV3OrdersOrderIdRefundsPostRequestShippingLinesInnerMethodId();

    /**
     * Model tests for WooCommerceWcV3OrdersOrderIdRefundsPostRequestShippingLinesInnerMethodId
     */
    @Test
    public void testWooCommerceWcV3OrdersOrderIdRefundsPostRequestShippingLinesInnerMethodId() {
        // TODO: test WooCommerceWcV3OrdersOrderIdRefundsPostRequestShippingLinesInnerMethodId
    }

}
