/*
 * Dev Store API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.9.1
 * Contact: admin@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.woocommerce.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.net.URI;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for WooCommerceWcV3OrdersPostRequestLineItemsInnerImage
 */
public class WooCommerceWcV3OrdersPostRequestLineItemsInnerImageTest {
    private final WooCommerceWcV3OrdersPostRequestLineItemsInnerImage model = new WooCommerceWcV3OrdersPostRequestLineItemsInnerImage();

    /**
     * Model tests for WooCommerceWcV3OrdersPostRequestLineItemsInnerImage
     */
    @Test
    public void testWooCommerceWcV3OrdersPostRequestLineItemsInnerImage() {
        // TODO: test WooCommerceWcV3OrdersPostRequestLineItemsInnerImage
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'src'
     */
    @Test
    public void srcTest() {
        // TODO: test src
    }

}
