/*
 * Dev Store API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.9.1
 * Contact: admin@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.woocommerce.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.woocommerce.model.WooCommerceProductVariationImage;
import com.woocommerce.model.WooCommerceShopCouponMetaDataInner;
import com.woocommerce.model.WooCommerceWcV3ProductsPostRequestDefaultAttributesInner;
import com.woocommerce.model.WooCommerceWcV3ProductsPostRequestDownloadsInner;
import com.woocommerce.model.WooCommerceWcV3ProductsProductIdVariationsPostRequestDimensions;
import com.woocommerce.model.WooCommerceWcV3ProductsProductIdVariationsPostRequestManageStock;
import java.io.IOException;
import java.net.URI;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for WooCommerceProductVariation
 */
public class WooCommerceProductVariationTest {
    private final WooCommerceProductVariation model = new WooCommerceProductVariation();

    /**
     * Model tests for WooCommerceProductVariation
     */
    @Test
    public void testWooCommerceProductVariation() {
        // TODO: test WooCommerceProductVariation
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'dateCreated'
     */
    @Test
    public void dateCreatedTest() {
        // TODO: test dateCreated
    }

    /**
     * Test the property 'dateModified'
     */
    @Test
    public void dateModifiedTest() {
        // TODO: test dateModified
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'permalink'
     */
    @Test
    public void permalinkTest() {
        // TODO: test permalink
    }

    /**
     * Test the property 'sku'
     */
    @Test
    public void skuTest() {
        // TODO: test sku
    }

    /**
     * Test the property 'globalUniqueId'
     */
    @Test
    public void globalUniqueIdTest() {
        // TODO: test globalUniqueId
    }

    /**
     * Test the property 'price'
     */
    @Test
    public void priceTest() {
        // TODO: test price
    }

    /**
     * Test the property 'regularPrice'
     */
    @Test
    public void regularPriceTest() {
        // TODO: test regularPrice
    }

    /**
     * Test the property 'salePrice'
     */
    @Test
    public void salePriceTest() {
        // TODO: test salePrice
    }

    /**
     * Test the property 'dateOnSaleFrom'
     */
    @Test
    public void dateOnSaleFromTest() {
        // TODO: test dateOnSaleFrom
    }

    /**
     * Test the property 'dateOnSaleFromGmt'
     */
    @Test
    public void dateOnSaleFromGmtTest() {
        // TODO: test dateOnSaleFromGmt
    }

    /**
     * Test the property 'dateOnSaleTo'
     */
    @Test
    public void dateOnSaleToTest() {
        // TODO: test dateOnSaleTo
    }

    /**
     * Test the property 'dateOnSaleToGmt'
     */
    @Test
    public void dateOnSaleToGmtTest() {
        // TODO: test dateOnSaleToGmt
    }

    /**
     * Test the property 'onSale'
     */
    @Test
    public void onSaleTest() {
        // TODO: test onSale
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'purchasable'
     */
    @Test
    public void purchasableTest() {
        // TODO: test purchasable
    }

    /**
     * Test the property 'virtual'
     */
    @Test
    public void virtualTest() {
        // TODO: test virtual
    }

    /**
     * Test the property 'downloadable'
     */
    @Test
    public void downloadableTest() {
        // TODO: test downloadable
    }

    /**
     * Test the property 'downloads'
     */
    @Test
    public void downloadsTest() {
        // TODO: test downloads
    }

    /**
     * Test the property 'downloadLimit'
     */
    @Test
    public void downloadLimitTest() {
        // TODO: test downloadLimit
    }

    /**
     * Test the property 'downloadExpiry'
     */
    @Test
    public void downloadExpiryTest() {
        // TODO: test downloadExpiry
    }

    /**
     * Test the property 'taxStatus'
     */
    @Test
    public void taxStatusTest() {
        // TODO: test taxStatus
    }

    /**
     * Test the property 'taxClass'
     */
    @Test
    public void taxClassTest() {
        // TODO: test taxClass
    }

    /**
     * Test the property 'manageStock'
     */
    @Test
    public void manageStockTest() {
        // TODO: test manageStock
    }

    /**
     * Test the property 'stockQuantity'
     */
    @Test
    public void stockQuantityTest() {
        // TODO: test stockQuantity
    }

    /**
     * Test the property 'stockStatus'
     */
    @Test
    public void stockStatusTest() {
        // TODO: test stockStatus
    }

    /**
     * Test the property 'backorders'
     */
    @Test
    public void backordersTest() {
        // TODO: test backorders
    }

    /**
     * Test the property 'backordersAllowed'
     */
    @Test
    public void backordersAllowedTest() {
        // TODO: test backordersAllowed
    }

    /**
     * Test the property 'backordered'
     */
    @Test
    public void backorderedTest() {
        // TODO: test backordered
    }

    /**
     * Test the property 'lowStockAmount'
     */
    @Test
    public void lowStockAmountTest() {
        // TODO: test lowStockAmount
    }

    /**
     * Test the property 'weight'
     */
    @Test
    public void weightTest() {
        // TODO: test weight
    }

    /**
     * Test the property 'dimensions'
     */
    @Test
    public void dimensionsTest() {
        // TODO: test dimensions
    }

    /**
     * Test the property 'shippingClass'
     */
    @Test
    public void shippingClassTest() {
        // TODO: test shippingClass
    }

    /**
     * Test the property 'shippingClassId'
     */
    @Test
    public void shippingClassIdTest() {
        // TODO: test shippingClassId
    }

    /**
     * Test the property 'image'
     */
    @Test
    public void imageTest() {
        // TODO: test image
    }

    /**
     * Test the property 'attributes'
     */
    @Test
    public void attributesTest() {
        // TODO: test attributes
    }

    /**
     * Test the property 'menuOrder'
     */
    @Test
    public void menuOrderTest() {
        // TODO: test menuOrder
    }

    /**
     * Test the property 'metaData'
     */
    @Test
    public void metaDataTest() {
        // TODO: test metaData
    }

    /**
     * Test the property 'parentId'
     */
    @Test
    public void parentIdTest() {
        // TODO: test parentId
    }

}
