/*
 * Dev Store API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.9.1
 * Contact: admin@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.woocommerce.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for WooCommerceOrderNote
 */
public class WooCommerceOrderNoteTest {
    private final WooCommerceOrderNote model = new WooCommerceOrderNote();

    /**
     * Model tests for WooCommerceOrderNote
     */
    @Test
    public void testWooCommerceOrderNote() {
        // TODO: test WooCommerceOrderNote
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'author'
     */
    @Test
    public void authorTest() {
        // TODO: test author
    }

    /**
     * Test the property 'dateCreated'
     */
    @Test
    public void dateCreatedTest() {
        // TODO: test dateCreated
    }

    /**
     * Test the property 'dateCreatedGmt'
     */
    @Test
    public void dateCreatedGmtTest() {
        // TODO: test dateCreatedGmt
    }

    /**
     * Test the property 'note'
     */
    @Test
    public void noteTest() {
        // TODO: test note
    }

    /**
     * Test the property 'customerNote'
     */
    @Test
    public void customerNoteTest() {
        // TODO: test customerNote
    }

    /**
     * Test the property 'addedByUser'
     */
    @Test
    public void addedByUserTest() {
        // TODO: test addedByUser
    }

}
