/*
 * Dev Store API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.9.1
 * Contact: admin@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.woocommerce.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.woocommerce.model.WooCommerceSystemStatusActivePluginsInner;
import com.woocommerce.model.WooCommerceSystemStatusDatabase;
import com.woocommerce.model.WooCommerceSystemStatusEnvironment;
import com.woocommerce.model.WooCommerceSystemStatusLogging;
import com.woocommerce.model.WooCommerceSystemStatusPagesInner;
import com.woocommerce.model.WooCommerceSystemStatusSecurity;
import com.woocommerce.model.WooCommerceSystemStatusSettings;
import com.woocommerce.model.WooCommerceSystemStatusTheme;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for WooCommerceSystemStatus
 */
public class WooCommerceSystemStatusTest {
    private final WooCommerceSystemStatus model = new WooCommerceSystemStatus();

    /**
     * Model tests for WooCommerceSystemStatus
     */
    @Test
    public void testWooCommerceSystemStatus() {
        // TODO: test WooCommerceSystemStatus
    }

    /**
     * Test the property 'environment'
     */
    @Test
    public void environmentTest() {
        // TODO: test environment
    }

    /**
     * Test the property 'database'
     */
    @Test
    public void databaseTest() {
        // TODO: test database
    }

    /**
     * Test the property 'activePlugins'
     */
    @Test
    public void activePluginsTest() {
        // TODO: test activePlugins
    }

    /**
     * Test the property 'inactivePlugins'
     */
    @Test
    public void inactivePluginsTest() {
        // TODO: test inactivePlugins
    }

    /**
     * Test the property 'dropinsMuPlugins'
     */
    @Test
    public void dropinsMuPluginsTest() {
        // TODO: test dropinsMuPlugins
    }

    /**
     * Test the property 'theme'
     */
    @Test
    public void themeTest() {
        // TODO: test theme
    }

    /**
     * Test the property 'settings'
     */
    @Test
    public void settingsTest() {
        // TODO: test settings
    }

    /**
     * Test the property 'security'
     */
    @Test
    public void securityTest() {
        // TODO: test security
    }

    /**
     * Test the property 'pages'
     */
    @Test
    public void pagesTest() {
        // TODO: test pages
    }

    /**
     * Test the property 'postTypeCounts'
     */
    @Test
    public void postTypeCountsTest() {
        // TODO: test postTypeCounts
    }

    /**
     * Test the property 'logging'
     */
    @Test
    public void loggingTest() {
        // TODO: test logging
    }

}
