/*
 * Dev Store API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.9.1
 * Contact: admin@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.woocommerce.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.woocommerce.model.WooCommerceShopCouponMetaDataInner;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for WooCommerceShopOrderRefundTaxLinesInner
 */
public class WooCommerceShopOrderRefundTaxLinesInnerTest {
    private final WooCommerceShopOrderRefundTaxLinesInner model = new WooCommerceShopOrderRefundTaxLinesInner();

    /**
     * Model tests for WooCommerceShopOrderRefundTaxLinesInner
     */
    @Test
    public void testWooCommerceShopOrderRefundTaxLinesInner() {
        // TODO: test WooCommerceShopOrderRefundTaxLinesInner
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'rateCode'
     */
    @Test
    public void rateCodeTest() {
        // TODO: test rateCode
    }

    /**
     * Test the property 'rateId'
     */
    @Test
    public void rateIdTest() {
        // TODO: test rateId
    }

    /**
     * Test the property 'label'
     */
    @Test
    public void labelTest() {
        // TODO: test label
    }

    /**
     * Test the property 'compound'
     */
    @Test
    public void compoundTest() {
        // TODO: test compound
    }

    /**
     * Test the property 'taxTotal'
     */
    @Test
    public void taxTotalTest() {
        // TODO: test taxTotal
    }

    /**
     * Test the property 'shippingTaxTotal'
     */
    @Test
    public void shippingTaxTotalTest() {
        // TODO: test shippingTaxTotal
    }

    /**
     * Test the property 'metaData'
     */
    @Test
    public void metaDataTest() {
        // TODO: test metaData
    }

}
