/*
 * Dev Store API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.9.1
 * Contact: admin@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.woocommerce.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for WooCommerceWcV3ProductsPostRequestDimensions
 */
public class WooCommerceWcV3ProductsPostRequestDimensionsTest {
    private final WooCommerceWcV3ProductsPostRequestDimensions model = new WooCommerceWcV3ProductsPostRequestDimensions();

    /**
     * Model tests for WooCommerceWcV3ProductsPostRequestDimensions
     */
    @Test
    public void testWooCommerceWcV3ProductsPostRequestDimensions() {
        // TODO: test WooCommerceWcV3ProductsPostRequestDimensions
    }

    /**
     * Test the property 'length'
     */
    @Test
    public void lengthTest() {
        // TODO: test length
    }

    /**
     * Test the property 'width'
     */
    @Test
    public void widthTest() {
        // TODO: test width
    }

    /**
     * Test the property 'height'
     */
    @Test
    public void heightTest() {
        // TODO: test height
    }

}
