/*
 * Dev Store API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.9.1
 * Contact: admin@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.woocommerce.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.woocommerce.model.WooCommerceCustomerDownloadFile;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for WooCommerceCustomerDownload
 */
public class WooCommerceCustomerDownloadTest {
    private final WooCommerceCustomerDownload model = new WooCommerceCustomerDownload();

    /**
     * Model tests for WooCommerceCustomerDownload
     */
    @Test
    public void testWooCommerceCustomerDownload() {
        // TODO: test WooCommerceCustomerDownload
    }

    /**
     * Test the property 'downloadId'
     */
    @Test
    public void downloadIdTest() {
        // TODO: test downloadId
    }

    /**
     * Test the property 'downloadUrl'
     */
    @Test
    public void downloadUrlTest() {
        // TODO: test downloadUrl
    }

    /**
     * Test the property 'productId'
     */
    @Test
    public void productIdTest() {
        // TODO: test productId
    }

    /**
     * Test the property 'productName'
     */
    @Test
    public void productNameTest() {
        // TODO: test productName
    }

    /**
     * Test the property 'downloadName'
     */
    @Test
    public void downloadNameTest() {
        // TODO: test downloadName
    }

    /**
     * Test the property 'orderId'
     */
    @Test
    public void orderIdTest() {
        // TODO: test orderId
    }

    /**
     * Test the property 'orderKey'
     */
    @Test
    public void orderKeyTest() {
        // TODO: test orderKey
    }

    /**
     * Test the property 'downloadsRemaining'
     */
    @Test
    public void downloadsRemainingTest() {
        // TODO: test downloadsRemaining
    }

    /**
     * Test the property 'accessExpires'
     */
    @Test
    public void accessExpiresTest() {
        // TODO: test accessExpires
    }

    /**
     * Test the property 'accessExpiresGmt'
     */
    @Test
    public void accessExpiresGmtTest() {
        // TODO: test accessExpiresGmt
    }

    /**
     * Test the property '_file'
     */
    @Test
    public void _fileTest() {
        // TODO: test _file
    }

}
