/*
 * Dev Store API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.9.1
 * Contact: admin@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.woocommerce;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapter;
import com.google.gson.internal.bind.util.ISO8601Utils;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.google.gson.JsonElement;
import io.gsonfire.GsonFireBuilder;
import io.gsonfire.TypeSelector;

import okio.ByteString;

import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.StringReader;
import java.lang.reflect.Type;
import java.nio.charset.StandardCharsets;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.ParsePosition;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.OffsetDateTime;
import java.time.ZoneOffset;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.Locale;
import java.util.Map;
import java.util.HashMap;

/*
 * A JSON utility class
 *
 * NOTE: in the future, this class may be converted to static, which may break
 *       backward-compatibility
 */
public class JSON {
    private static Gson gson;
    private static boolean isLenientOnJson = false;
    private static DateTypeAdapter dateTypeAdapter = new DateTypeAdapter();
    private static SqlDateTypeAdapter sqlDateTypeAdapter = new SqlDateTypeAdapter();
    private static OffsetDateTimeTypeAdapter offsetDateTimeTypeAdapter = new OffsetDateTimeTypeAdapter();
    private static LocalDateTypeAdapter localDateTypeAdapter = new LocalDateTypeAdapter();
    private static ByteArrayAdapter byteArrayAdapter = new ByteArrayAdapter();

    @SuppressWarnings("unchecked")
    public static GsonBuilder createGson() {
        GsonFireBuilder fireBuilder = new GsonFireBuilder()
        ;
        GsonBuilder builder = fireBuilder.createGsonBuilder();
        return builder;
    }

    private static String getDiscriminatorValue(JsonElement readElement, String discriminatorField) {
        JsonElement element = readElement.getAsJsonObject().get(discriminatorField);
        if (null == element) {
            throw new IllegalArgumentException("missing discriminator field: <" + discriminatorField + ">");
        }
        return element.getAsString();
    }

    /**
     * Returns the Java class that implements the OpenAPI schema for the specified discriminator value.
     *
     * @param classByDiscriminatorValue The map of discriminator values to Java classes.
     * @param discriminatorValue The value of the OpenAPI discriminator in the input data.
     * @return The Java class that implements the OpenAPI schema
     */
    private static Class getClassByDiscriminator(Map classByDiscriminatorValue, String discriminatorValue) {
        Class clazz = (Class) classByDiscriminatorValue.get(discriminatorValue);
        if (null == clazz) {
            throw new IllegalArgumentException("cannot determine model class of name: <" + discriminatorValue + ">");
        }
        return clazz;
    }

    static {
        GsonBuilder gsonBuilder = createGson();
        gsonBuilder.registerTypeAdapter(Date.class, dateTypeAdapter);
        gsonBuilder.registerTypeAdapter(java.sql.Date.class, sqlDateTypeAdapter);
        gsonBuilder.registerTypeAdapter(OffsetDateTime.class, offsetDateTimeTypeAdapter);
        gsonBuilder.registerTypeAdapter(LocalDate.class, localDateTypeAdapter);
        gsonBuilder.registerTypeAdapter(byte[].class, byteArrayAdapter);
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceBatch.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceCustomer.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceCustomerDownload.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceCustomerDownloadFile.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceDataContinents.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceDataContinentsCountriesInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceDataContinentsCountriesInnerStatesInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceDataCountries.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceDataCurrencies.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceDataIndex.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceEmailTemplate.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceOrderActions.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceOrderNote.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceOrderStatus.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommercePaymentGateway.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceProduct.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceProductAttribute.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceProductAttributeTerm.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceProductBrand.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceProductBrandImage.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceProductCat.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceProductImagesInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceProductReview.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceProductReviewReviewerAvatarUrls.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceProductShippingClass.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceProductTag.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceProductVariation.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceProductVariationImage.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceReport.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceReportCouponTotal.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceReportCustomerTotal.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceReportOrderTotal.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceReportProductTotal.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceReportReviewTotal.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceSalesReport.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceSetting.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceSettingGroup.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceShippingMethod.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceShippingZone.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceShippingZoneLocation.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceShippingZoneMethod.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceShopCoupon.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceShopCouponMetaDataInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceShopOrder.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceShopOrderCouponLinesInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceShopOrderLineItemsInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceShopOrderLineItemsInnerMetaDataInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceShopOrderRefund.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceShopOrderRefundFeeLinesInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceShopOrderRefundLineItemsInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceShopOrderRefundLineItemsInnerTaxesInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceShopOrderRefundShippingLinesInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceShopOrderRefundTaxLinesInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceShopOrderRefundsInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceSystemStatus.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceSystemStatusActivePluginsInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceSystemStatusDatabase.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceSystemStatusEnvironment.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceSystemStatusLogging.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceSystemStatusPagesInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceSystemStatusSecurity.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceSystemStatusSettings.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceSystemStatusTheme.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceSystemStatusTool.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceTax.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceTaxClass.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceTopSellersReport.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceWcV3CouponsPostRequestAmount.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceWcV3CouponsPostRequestMaximumAmount.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceWcV3CouponsPostRequestMetaDataInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceWcV3CouponsPostRequestMetaDataInnerValue.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceWcV3CouponsPostRequestMinimumAmount.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceWcV3CustomersPostRequestBilling.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceWcV3CustomersPostRequestShipping.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceWcV3OrdersOrderIdRefundsPostRequestFeeLinesInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceWcV3OrdersOrderIdRefundsPostRequestFeeLinesInnerName.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceWcV3OrdersOrderIdRefundsPostRequestFeeLinesInnerTaxesInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceWcV3OrdersOrderIdRefundsPostRequestShippingLinesInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceWcV3OrdersOrderIdRefundsPostRequestShippingLinesInnerMethodId.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceWcV3OrdersOrderIdRefundsPostRequestShippingLinesInnerMethodTitle.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceWcV3OrdersOrderIdRefundsPostRequestShippingLinesInnerTaxesInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceWcV3OrdersPostRequestBilling.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceWcV3OrdersPostRequestCouponLinesInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceWcV3OrdersPostRequestCouponLinesInnerCode.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceWcV3OrdersPostRequestLineItemsInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceWcV3OrdersPostRequestLineItemsInnerImage.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceWcV3OrdersPostRequestLineItemsInnerMetaDataInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceWcV3OrdersPostRequestLineItemsInnerName.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceWcV3OrdersPostRequestLineItemsInnerProductId.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceWcV3OrdersPostRequestShipping.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceWcV3PaymentGatewaysIdPutRequestSettings.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceWcV3ProductsBrandsPostRequestImage.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceWcV3ProductsPostRequestAttributesInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceWcV3ProductsPostRequestBrandsInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceWcV3ProductsPostRequestCategoriesInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceWcV3ProductsPostRequestDefaultAttributesInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceWcV3ProductsPostRequestDimensions.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceWcV3ProductsPostRequestDownloadsInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceWcV3ProductsPostRequestImagesInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceWcV3ProductsPostRequestTagsInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceWcV3ProductsProductIdVariationsGeneratePostRequestDefaultValues.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceWcV3ProductsProductIdVariationsGeneratePostRequestDefaultValuesDimensions.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceWcV3ProductsProductIdVariationsGeneratePostRequestDefaultValuesImage.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceWcV3ProductsProductIdVariationsGeneratePostRequestDefaultValuesManageStock.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceWcV3ProductsProductIdVariationsIdPutRequestManageStock.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceWcV3ProductsProductIdVariationsPostRequestDimensions.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceWcV3ProductsProductIdVariationsPostRequestImage.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceWcV3ProductsProductIdVariationsPostRequestManageStock.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceWcV3SettingsGroupIdBatchPutRequestValue.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceWcV3ShippingZonesZoneIdMethodsPostRequestSettings.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.woocommerce.model.WooCommerceWebhook.CustomTypeAdapterFactory());
        gson = gsonBuilder.create();
    }

    /**
     * Get Gson.
     *
     * @return Gson
     */
    public static Gson getGson() {
        return gson;
    }

    /**
     * Set Gson.
     *
     * @param gson Gson
     */
    public static void setGson(Gson gson) {
        JSON.gson = gson;
    }

    public static void setLenientOnJson(boolean lenientOnJson) {
        isLenientOnJson = lenientOnJson;
    }

    /**
     * Serialize the given Java object into JSON string.
     *
     * @param obj Object
     * @return String representation of the JSON
     */
    public static String serialize(Object obj) {
        return gson.toJson(obj);
    }

    /**
     * Deserialize the given JSON string to Java object.
     *
     * @param <T>        Type
     * @param body       The JSON string
     * @param returnType The type to deserialize into
     * @return The deserialized Java object
     */
    @SuppressWarnings("unchecked")
    public static <T> T deserialize(String body, Type returnType) {
        try {
            if (isLenientOnJson) {
                JsonReader jsonReader = new JsonReader(new StringReader(body));
                // see https://google-gson.googlecode.com/svn/trunk/gson/docs/javadocs/com/google/gson/stream/JsonReader.html#setLenient(boolean)
                jsonReader.setLenient(true);
                return gson.fromJson(jsonReader, returnType);
            } else {
                return gson.fromJson(body, returnType);
            }
        } catch (JsonParseException e) {
            // Fallback processing when failed to parse JSON form response body:
            // return the response body string directly for the String return type;
            if (returnType.equals(String.class)) {
                return (T) body;
            } else {
                throw (e);
            }
        }
    }

    /**
    * Deserialize the given JSON InputStream to a Java object.
    *
    * @param <T>         Type
    * @param inputStream The JSON InputStream
    * @param returnType  The type to deserialize into
    * @return The deserialized Java object
    */
    @SuppressWarnings("unchecked")
    public static <T> T deserialize(InputStream inputStream, Type returnType) throws IOException {
        try (InputStreamReader reader = new InputStreamReader(inputStream, StandardCharsets.UTF_8)) {
        if (isLenientOnJson) {
            // see https://google-gson.googlecode.com/svn/trunk/gson/docs/javadocs/com/google/gson/stream/JsonReader.html#setLenient(boolean)
            JsonReader jsonReader = new JsonReader(reader);
            jsonReader.setLenient(true);
            return gson.fromJson(jsonReader, returnType);
            } else {
                return gson.fromJson(reader, returnType);
            }
        }
    }

    /**
     * Gson TypeAdapter for Byte Array type
     */
    public static class ByteArrayAdapter extends TypeAdapter<byte[]> {

        @Override
        public void write(JsonWriter out, byte[] value) throws IOException {
            if (value == null) {
                out.nullValue();
            } else {
                out.value(ByteString.of(value).base64());
            }
        }

        @Override
        public byte[] read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String bytesAsBase64 = in.nextString();
                    ByteString byteString = ByteString.decodeBase64(bytesAsBase64);
                    return byteString.toByteArray();
            }
        }
    }

    /**
     * Gson TypeAdapter for JSR310 OffsetDateTime type
     */
    public static class OffsetDateTimeTypeAdapter extends TypeAdapter<OffsetDateTime> {

        private DateTimeFormatter formatter;

        public OffsetDateTimeTypeAdapter() {
            this(DateTimeFormatter.ISO_OFFSET_DATE_TIME);
        }

        public OffsetDateTimeTypeAdapter(DateTimeFormatter formatter) {
            this.formatter = formatter;
        }

        public void setFormat(DateTimeFormatter dateFormat) {
            this.formatter = dateFormat;
        }

        @Override
        public void write(JsonWriter out, OffsetDateTime date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                out.value(formatter.format(date));
            }
        }

        @Override
        public OffsetDateTime read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String date = in.nextString();
                    if (date.endsWith("+0000")) {
                        date = date.substring(0, date.length()-5) + "Z";
                    }
                    // WooCommerce returns dates without timezone offset (e.g., "2026-02-04T06:17:28")
                    // which is exactly 19 chars. Dates with offset are longer (Z, +00:00, etc.)
                    if (date.length() == 19) {
                        return LocalDateTime.parse(date, DateTimeFormatter.ISO_LOCAL_DATE_TIME).atOffset(ZoneOffset.UTC);
                    }
                    return OffsetDateTime.parse(date, formatter);
            }
        }
    }

    /**
     * Gson TypeAdapter for JSR310 LocalDate type
     */
    public static class LocalDateTypeAdapter extends TypeAdapter<LocalDate> {

        private DateTimeFormatter formatter;

        public LocalDateTypeAdapter() {
            this(DateTimeFormatter.ISO_LOCAL_DATE);
        }

        public LocalDateTypeAdapter(DateTimeFormatter formatter) {
            this.formatter = formatter;
        }

        public void setFormat(DateTimeFormatter dateFormat) {
            this.formatter = dateFormat;
        }

        @Override
        public void write(JsonWriter out, LocalDate date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                out.value(formatter.format(date));
            }
        }

        @Override
        public LocalDate read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String date = in.nextString();
                    return LocalDate.parse(date, formatter);
            }
        }
    }

    public static void setOffsetDateTimeFormat(DateTimeFormatter dateFormat) {
        offsetDateTimeTypeAdapter.setFormat(dateFormat);
    }

    public static void setLocalDateFormat(DateTimeFormatter dateFormat) {
        localDateTypeAdapter.setFormat(dateFormat);
    }

    /**
     * Gson TypeAdapter for java.sql.Date type
     * If the dateFormat is null, a simple "yyyy-MM-dd" format will be used
     * (more efficient than SimpleDateFormat).
     */
    public static class SqlDateTypeAdapter extends TypeAdapter<java.sql.Date> {

        private DateFormat dateFormat;

        public SqlDateTypeAdapter() {}

        public SqlDateTypeAdapter(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        public void setFormat(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        @Override
        public void write(JsonWriter out, java.sql.Date date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                String value;
                if (dateFormat != null) {
                    value = dateFormat.format(date);
                } else {
                    value = date.toString();
                }
                out.value(value);
            }
        }

        @Override
        public java.sql.Date read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String date = in.nextString();
                    try {
                        if (dateFormat != null) {
                            return new java.sql.Date(dateFormat.parse(date).getTime());
                        }
                        return new java.sql.Date(ISO8601Utils.parse(date, new ParsePosition(0)).getTime());
                    } catch (ParseException e) {
                        throw new JsonParseException(e);
                    }
            }
        }
    }

    /**
     * Gson TypeAdapter for java.util.Date type
     * If the dateFormat is null, ISO8601Utils will be used.
     */
    public static class DateTypeAdapter extends TypeAdapter<Date> {

        private DateFormat dateFormat;

        public DateTypeAdapter() {}

        public DateTypeAdapter(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        public void setFormat(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        @Override
        public void write(JsonWriter out, Date date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                String value;
                if (dateFormat != null) {
                    value = dateFormat.format(date);
                } else {
                    value = ISO8601Utils.format(date, true);
                }
                out.value(value);
            }
        }

        @Override
        public Date read(JsonReader in) throws IOException {
            try {
                switch (in.peek()) {
                    case NULL:
                        in.nextNull();
                        return null;
                    default:
                        String date = in.nextString();
                        try {
                            if (dateFormat != null) {
                                return dateFormat.parse(date);
                            }
                            return ISO8601Utils.parse(date, new ParsePosition(0));
                        } catch (ParseException e) {
                            throw new JsonParseException(e);
                        }
                }
            } catch (IllegalArgumentException e) {
                throw new JsonParseException(e);
            }
        }
    }

    public static void setDateFormat(DateFormat dateFormat) {
        dateTypeAdapter.setFormat(dateFormat);
    }

    public static void setSqlDateFormat(DateFormat dateFormat) {
        sqlDateTypeAdapter.setFormat(dateFormat);
    }
}
